#!/bin/bash
set -euo pipefail
GOV="$1"; ROOT="$2"
echo "=== AC-16 Cross-capability: U ↔ O5 (health SLOs observed by scheduler) ==="
echo "The doctor checks (U) are the SLO observations."
echo "The audit (O5) runs the governance suite which observes check states."
echo "D021 (doctor) checks governance suite currency (O4 ↔ U interaction)."
echo ""
echo "--- Exercise: run audit, check D021 reports it green ---"
$GOV audit --root "$ROOT" --json 2>&1 | python3 -c "import json,sys; d=json.load(sys.stdin); print('audit verdict:', d['result']['verdict'])"
$GOV doctor --root "$ROOT" --json 2>&1 | python3 -c "import json,sys; d=json.load(sys.stdin); [print('D021:', c['ok'], c['message']) for c in d['result']['checks'] if c['id']=='D021']"
echo ""

echo "=== AC-16 Cross-capability: O4 ↔ W6 (staleness) ==="
echo "O4 says: a green result becomes stale when relevant inputs change."
echo "This was demonstrated in O3-O4 probe: mutating PROJECT_POLICY makes D021 fail."
echo "W6 is not owned by this family (Gate W is another auditor), but the mechanism"
echo "is shared: inputs_hash tracks governance/kernel, governance/project, spec/decisions, etc."
echo ""
echo "--- inputs_hash function covers these dirs ---"
grep -A10 "pub fn inputs_hash" "$3/runtime/src/verification/mod.rs"
