//! **Governed work generated from events** (BC-P2-24; Contract v3:571-583 I3 "Tasks can be generated from: readiness
//! gaps, failed tests, audit findings, research discoveries, human decisions, CIT effects, lessons, missing
//! tools/skills, retrieval failures, security findings, performance regressions"; framework §43 "The WBS is therefore
//! a continuously compiled execution graph, not a static plan"; frozen gate contract AC-5 "remediation/task
//! generation", from each health failure).
//!
//! ## One engine, every source
//!
//! Each source is a **detector over what the event durably left** — a recorded product-test run, the health state and
//! the governance-suite record, a worker's return and a sealed close report, a decision derived from a human answer,
//! a completed task a CIT marked for revalidation, a lesson record, a task requiring a tool or skill that does not
//! resolve, a failure-memory record, a telemetry measurement — never a label the caller asserts. For every occurrence
//! it proposes one piece of work ([`Candidate`]); [`reconcile`] turns the proposals into governed, linked tasks in the
//! same DAG as all other work:
//!
//! | source | detected from | the work |
//! |---|---|---|
//! | failed tests (:574) | the latest honoured product-test records (`verification::product`): a family failing in its latest run | `repair` the family (derived from the failing run) |
//! | audit findings (:575), each health failure (AC-5, O5) | the health scheduler state (families and doctor checks failing at or above the policy severity) with the findings of the latest honoured governance-suite record | remediate the check (`remedies: [check]`) |
//! | security findings (:582) | the same, for security checks (secrets, T2 bindings, kernel/installation integrity, plugins) | `security` remediation of the named paths |
//! | research discoveries (:576) | worker returns (`handoff return`) and sealed close reports: `discoveries`, `unresolved`, `proposed_decisions` | follow up each item (`discovery` / `decision-preparation`) |
//! | human decisions (:577) | T2-verified decisions derived from a human answer to a gate an agent raised | carry the decision out; replan the work a declining answer stops |
//! | CIT effects (:578) | completed work a CIT marked `revalidation.required` with no revalidation task (propagation generates it when it may; this completes it when it could not) | `validation` that `revalidates` the work |
//! | lessons (:579) | lesson records (candidate or active) | act on the lesson or route it upstream |
//! | missing tools/skills (:580) | open tasks whose `required_tools` / `required_skills` do not resolve (`dag::InputResolver`) | provide it; the task `blocks` every task that needs it |
//! | retrieval failures (:581) and other failure memory | open failure-memory records (`memory::failures::open_failures`) | root-cause and repair; the record's `follow_up` is linked to the task (`link_follow_up`) |
//! | performance regressions (:583) | telemetry measurements against their declared baseline or their own history | a durable `regression` failure record, then `performance` work linked to it |
//!
//! Readiness gaps (:573) are generated by the readiness planner (`readiness::plan`); W7 orphans by the lineage family's
//! remediation (`verification::lineage`, WS-2); revalidation of completed work by upstream-change propagation
//! (`cit::propagation`, WS-4). The engine **adopts** that work ([`source_of`]): it counts as the generated work of
//! its source, so the engine never duplicates it, and it is listed with everything else (`gov task generate`).
//!
//! ## Linked, idempotent, governed
//!
//! * **Linked.** A generated task is `derived_from` its source record(s) (a DERIVED_FROM edge in the graph, and the
//!   source is delivered to the worker as evidence), carries `generation: {source, subject, key, occurrence,
//!   records, detected_by, detected_at, contract, detail}`, `blocks` the tasks it unblocks and `AFFECTS` the tasks it
//!   replans. A failure record's `follow_up.task` names it.
//! * **Idempotent.** An occurrence has a stable key (source, subject and what occurred); at most one task exists per
//!   key, and at most one open task per source subject. A cancelled task means "not for this occurrence"; after a
//!   completed task, the same subject generates again only on evidence newer than that completion.
//! * **Governed.** Tasks are created through `tasks::create_generated`: the write guard applies (nothing is generated
//!   under FREEZE_WRITES / PAUSE, below floor or on an unverified kernel), the status is the one the DAG derives, the
//!   provenance is the generator's, and the designated role and class come from the kernel taxonomy
//!   (`taxonomy/WORK_GENERATION.yaml`). Remediation of a health failure names the check it `remedies`, so it stays
//!   available under the hard-block it remedies (availability rule) and still commits only by clearing it.
//! * **When the event occurs.** [`reconcile`] runs after every governed write command (`after_command`, the CLI's
//!   one post-command site), inside `task close`, `continue` and `task replan`, and on demand (`gov task generate`).
//!   Read-only commands never write: an event a read-only command observes and records durably (a retrieval miss, a
//!   doctor result in the health state) is turned into work by the next governed operation.
//! * **No loops.** Findings about generated work itself never generate work.
use crate::orchestration::control;
use crate::records::{Record, RecordStore};
use crate::util::{now_iso, sha256_hex};
use crate::{GovError, Project, Result};
use serde_json::{json, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::sync::atomic::{AtomicBool, Ordering};

/// The producer every generated task records (`provenance.producer`, `generation`).
pub const GENERATOR: &str = "gov work generation";

/// The kernel taxonomy this engine reads, embedded for installations that predate it.
const DEFAULT_TAXONOMY: &str = include_str!("../../../framework/taxonomy/WORK_GENERATION.yaml");

/// Producer of W7 investigation tasks (`verification::lineage::GENERATOR`), adopted.
const W7_GENERATOR: &str = "health:lineage_orphans";

/// Set once this process has reconciled, so the post-command site does not repeat an operation's own reconciliation.
static RECONCILED: AtomicBool = AtomicBool::new(false);

/// Labels of commands after which the post-command site does not generate: lifecycle ingress and recovery (the
/// project's kernel or layout is being established or changed), emergency controls, and the regeneration of the OS's
/// own derived views (a rebuild of derived state must never change project truth: framework §19, Contract v3 B3).
const QUIET_AFTER: &[&str] = &[
    "rebuild-memory",
    "memory rebuild",
    "context compile",
    "adapters generate",
    "tools registry",
    "init",
    "adopt",
    "migrate",
    "update",
    "kernel",
    "recover",
    "pause",
    "freeze-writes",
    "cancel-agents",
    "resume",
    "task generate",
];

// ------------------------------------------------------------------------------------------------ configuration

/// The kernel taxonomy `taxonomy/WORK_GENERATION.yaml` (the installed kernel's copy; the embedded one when the
/// installation predates it).
#[derive(Debug, Clone)]
pub struct Config {
    raw: Value,
}

impl Config {
    pub fn load(p: &Project) -> Config {
        let installed = p.kernel_dir().join("taxonomy").join("WORK_GENERATION.yaml");
        let raw = crate::util::read_yaml(&installed)
            .ok()
            .filter(|v| v.get("sources").is_some())
            .unwrap_or_else(Self::embedded_raw);
        Config { raw }
    }
    fn embedded_raw() -> Value {
        serde_yaml::from_str(DEFAULT_TAXONOMY).unwrap_or(json!({}))
    }
    /// The embedded taxonomy (tests; installations that predate it).
    pub fn embedded() -> Config {
        Config {
            raw: Self::embedded_raw(),
        }
    }
    fn list(&self, key: &str) -> Vec<String> {
        self.raw[key]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default()
    }
    /// `(class, designated role, allowed paths, contract line)` of a source.
    pub fn source(&self, kind: &str) -> (String, Option<String>, Vec<String>, String) {
        let s = &self.raw["sources"][kind];
        (
            s["class"].as_str().unwrap_or("governance").to_string(),
            s["role"]
                .as_str()
                .filter(|r| !r.is_empty())
                .map(|r| r.to_string()),
            s["paths"]
                .as_array()
                .map(|a| {
                    a.iter()
                        .filter_map(|x| x.as_str().map(|s| s.to_string()))
                        .collect()
                })
                .unwrap_or_default(),
            s["contract"]
                .as_str()
                .unwrap_or("Contract v3:571-583")
                .to_string(),
        )
    }
    pub fn severity_threshold(&self) -> String {
        self.raw["severity_threshold"]
            .as_str()
            .unwrap_or("medium")
            .to_string()
    }
    fn canonical_check(&self, id: &str) -> String {
        self.raw["same_condition"][id]
            .as_str()
            .unwrap_or(id)
            .to_string()
    }
    fn trivial(&self, item: &str) -> bool {
        let t = item.trim().trim_end_matches('.').to_lowercase();
        t.len() < 2 || self.list("trivial_items").iter().any(|x| *x == t)
    }
    fn perf(&self, key: &str) -> Value {
        self.raw["performance"][key].clone()
    }
}

// ------------------------------------------------------------------------------------------------ candidates

/// One piece of work an event calls for.
#[derive(Debug, Clone, Default)]
pub struct Candidate {
    /// Source kind (a key of the taxonomy's `sources`).
    pub source: String,
    /// What the work is about, stable across occurrences (a check, a family, a record, a tool, …).
    pub subject: String,
    /// What occurred (a record id, or a digest of what failed): with source and subject it keys the work.
    pub occurrence: String,
    /// When the evidence of the occurrence was produced (RFC 3339 or a date).
    pub evidence_at: String,
    /// Governed source records the work is derived from.
    pub records: Vec<String>,
    pub title: String,
    pub objective: String,
    /// Allowed paths (empty = the taxonomy's for the source).
    pub paths: Vec<String>,
    /// Tasks the work unblocks (its `blocks`).
    pub blocks: Vec<String>,
    /// Records the work acts on (`AFFECTS` relations).
    pub affects: Vec<String>,
    /// Health checks the work remedies.
    pub remedies: Vec<String>,
    /// Failure-memory record to link to the task (`memory::failures::link_follow_up`).
    pub failure: Option<String>,
    /// Extra task fields (e.g. the inputs of the work a revalidation task revalidates).
    pub fields: Value,
    pub detail: Value,
}

impl Candidate {
    /// The occurrence key: `GEN-` + 16 hex of source, subject and occurrence.
    pub fn key(&self) -> String {
        key_of(&self.source, &self.subject, &self.occurrence)
    }
    pub fn to_value(&self) -> Value {
        json!({"source": self.source, "subject": self.subject, "occurrence": self.occurrence, "key": self.key(),
               "evidence_at": self.evidence_at, "records": self.records, "title": self.title, "blocks": self.blocks,
               "affects": self.affects, "remedies": self.remedies, "failure": self.failure})
    }
}

pub fn key_of(source: &str, subject: &str, occurrence: &str) -> String {
    format!(
        "GEN-{}",
        &sha256_hex(format!("{source}\u{1f}{subject}\u{1f}{occurrence}").as_bytes())[..16]
    )
}

fn digest(parts: &[String]) -> String {
    sha256_hex(parts.join("\u{1f}").as_bytes())[..16].to_string()
}

/// Epoch seconds of an RFC 3339 timestamp or a `YYYY-MM-DD` date.
fn epoch(s: &str) -> Option<i64> {
    if let Ok(d) = chrono::DateTime::parse_from_rfc3339(s) {
        return Some(d.timestamp());
    }
    chrono::NaiveDate::parse_from_str(s.get(..10).unwrap_or(s), "%Y-%m-%d")
        .ok()
        .and_then(|d| d.and_hms_opt(0, 0, 0))
        .map(|d| d.and_utc().timestamp())
}

fn text_of(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Object(o) => ["text", "description", "summary", "title", "question", "id"]
            .iter()
            .find_map(|k| o.get(*k).and_then(|x| x.as_str()).map(|s| s.to_string()))
            .unwrap_or_else(|| v.to_string()),
        Value::Null => String::new(),
        other => other.to_string(),
    }
}

fn clip(s: &str, n: usize) -> String {
    let t: String = s.chars().take(n).collect();
    if t.len() < s.len() {
        format!("{t}…")
    } else {
        t
    }
}

// ------------------------------------------------------------------------------------------------ existing work

/// A task that is the generated work of some source (generated here, or adopted).
#[derive(Debug, Clone)]
pub struct Generated {
    pub task: String,
    pub status: String,
    pub source: String,
    pub subject: String,
    pub key: String,
    /// The occurrence key without its recurrence suffix.
    pub base_key: String,
    pub closed_at: String,
    pub blocks: Vec<String>,
    pub adopted: bool,
}

impl Generated {
    fn open(&self) -> bool {
        !matches!(self.status.as_str(), "DONE" | "CANCELLED")
    }
}

/// **Which event a task was generated from**, for generated and adopted work: the generation block this engine writes;
/// W7 orphan investigations (`generated_by: health:lineage_orphans`, `investigates`); revalidation tasks
/// (`revalidates`, generated by upstream-change propagation); readiness gap tasks (`generated_by:
/// readiness-planner`). `None` for work an operator created.
pub fn source_of(t: &Record) -> Option<Value> {
    if let Some(g) = t.data.get("generation").filter(|g| g.is_object()) {
        return Some(
            json!({"source": g["source"], "subject": g["subject"], "key": g["key"], "records": g["records"], "detected_by": g["detected_by"], "generator": GENERATOR}),
        );
    }
    if t.get("generated_by") == W7_GENERATOR {
        return Some(
            json!({"source": "orphan", "subject": t.data["investigates"]["subject"], "key": t.data["investigates"]["key"], "adopted": true, "generator": W7_GENERATOR, "contract": "Contract v3:1138-1144 W7"}),
        );
    }
    let rv = t.get("revalidates");
    if !rv.is_empty() {
        return Some(
            json!({"source": "cit-effect", "subject": rv, "key": key_of("cit-effect", &rv, &rv), "adopted": !t.data.get("generation").is_some(), "generator": t.get("generated_by"), "contract": "Contract v3:578; :1134"}),
        );
    }
    if t.get("generated_by") == "readiness-planner" {
        let subject = format!("{}#{}", t.get("feature"), t.get("readiness_cell"));
        return Some(
            json!({"source": "readiness-gap", "subject": subject, "key": key_of("readiness-gap", &subject, &subject), "adopted": true, "generator": "readiness-planner", "contract": "Contract v3:573"}),
        );
    }
    None
}

/// Every generated or adopted task.
pub fn existing(store: &RecordStore) -> Vec<Generated> {
    let mut out = vec![];
    for t in store.of_type("task") {
        let Some(s) = source_of(t) else { continue };
        let key = s["key"].as_str().unwrap_or("").to_string();
        let base_key = t.data["generation"]["base_key"]
            .as_str()
            .map(|x| x.to_string())
            .unwrap_or_else(|| key.clone());
        out.push(Generated {
            task: t.id(),
            status: t.get("task_status"),
            source: s["source"].as_str().unwrap_or("").to_string(),
            subject: match &s["subject"] {
                Value::String(x) => x.clone(),
                Value::Null => String::new(),
                other => other.to_string(),
            },
            key,
            base_key,
            closed_at: t.get("closed_at"),
            blocks: t.list("blocks"),
            adopted: s["adopted"].as_bool().unwrap_or(false),
        });
    }
    out
}

/// What [`reconcile`] does with a candidate.
#[derive(Debug, Clone, PartialEq)]
pub enum Decision {
    /// Generate a task under this key (a recurrence carries a suffix).
    Create { key: String, recurrence: usize },
    /// Add the candidate's `blocks` to this open task (missing tools/skills needed by more work).
    Augment {
        task: String,
        add_blocks: Vec<String>,
    },
    /// Nothing to do, with why.
    Skip {
        reason: String,
        task: Option<String>,
    },
}

/// **The idempotency rule.** At most one task per occurrence key and at most one open task per source subject; a
/// cancelled task declines its occurrence; after a completed task, the subject generates again only on evidence
/// newer than that completion (the remedy did not hold).
pub fn decide(c: &Candidate, ex: &[Generated]) -> Decision {
    let base = c.key();
    let same_subject: Vec<&Generated> = ex
        .iter()
        .filter(|g| g.source == c.source && g.subject == c.subject)
        .collect();
    if let Some(g) = same_subject.iter().find(|g| g.open()) {
        let add: Vec<String> = c
            .blocks
            .iter()
            .filter(|b| !g.blocks.contains(b) && **b != g.task)
            .cloned()
            .collect();
        if !add.is_empty() && !g.adopted {
            return Decision::Augment {
                task: g.task.clone(),
                add_blocks: add,
            };
        }
        return Decision::Skip {
            reason: "open work for this subject exists".into(),
            task: Some(g.task.clone()),
        };
    }
    let same_occurrence: Vec<&&Generated> = same_subject
        .iter()
        .filter(|g| g.base_key == base || g.key == base)
        .collect();
    if let Some(g) = same_occurrence.iter().find(|g| g.status == "CANCELLED") {
        return Decision::Skip {
            reason: "work for this occurrence was cancelled".into(),
            task: Some(g.task.clone()),
        };
    }
    let evidence = epoch(&c.evidence_at);
    let latest_done = same_subject
        .iter()
        .filter(|g| g.status == "DONE")
        .max_by_key(|g| epoch(&g.closed_at).unwrap_or(0));
    if let Some(d) = latest_done {
        let done_at = epoch(&d.closed_at).unwrap_or(i64::MAX);
        if evidence.map(|e| e <= done_at).unwrap_or(true) {
            return Decision::Skip {
                reason: "the evidence predates the completed work for this subject".into(),
                task: Some(d.task.clone()),
            };
        }
        let n = same_occurrence
            .iter()
            .filter(|g| g.status == "DONE")
            .count();
        if n > 0 {
            return Decision::Create {
                key: format!("{base}-r{n}"),
                recurrence: n,
            };
        }
    }
    if let Some(g) = ex.iter().find(|g| g.key == base) {
        return Decision::Skip {
            reason: "already generated".into(),
            task: Some(g.task.clone()),
        };
    }
    Decision::Create {
        key: base,
        recurrence: 0,
    }
}

// ------------------------------------------------------------------------------------------------ sources

/// Everything a source reads, once per reconciliation.
pub struct GenCtx<'a> {
    pub p: &'a Project,
    pub store: &'a RecordStore,
    pub cfg: Config,
    /// Ids and paths of generated/adopted tasks (findings about them never generate work).
    generated_tasks: BTreeSet<String>,
}

impl<'a> GenCtx<'a> {
    pub fn new(p: &'a Project, store: &'a RecordStore) -> Self {
        let mut generated_tasks = BTreeSet::new();
        for t in store.of_type("task") {
            if source_of(t).is_some() {
                generated_tasks.insert(t.id());
                generated_tasks.insert(t.path.clone());
            }
        }
        GenCtx {
            p,
            store,
            cfg: Config::load(p),
            generated_tasks,
        }
    }
    fn about_generated_work(&self, f: &Value) -> bool {
        let path = f["path"].as_str().unwrap_or("");
        let msg = f["message"].as_str().unwrap_or("");
        (!path.is_empty() && self.generated_tasks.contains(path))
            || self
                .generated_tasks
                .iter()
                .any(|t| t.starts_with("TASK-") && msg.contains(t.as_str()))
    }
    /// Ids of `ids` that are current governed records a `derived_from` link may name: a graph edge must reach an
    /// indexed record, so memory-quality events (never indexed, `memory::failures::MEMORY_QUALITY_DIR`) are linked
    /// the other way — the failure record's `follow_up.task` — and named in `generation.records`.
    fn linkable(&self, ids: &[String]) -> Vec<String> {
        let excluded = ["SUPERSEDED", "HISTORICAL", "REJECTED", "RETIRED", "LEGACY"];
        ids.iter()
            .filter(|i| {
                self.store
                    .get(i)
                    .map(|r| {
                        !excluded.contains(&r.status().as_str())
                            && !crate::memory::failures::is_memory_quality_path(&r.path)
                    })
                    .unwrap_or(false)
            })
            .cloned()
            .collect()
    }
}

/// **Failed tests** (Contract v3:574): a product-test family whose latest recorded run failed. The occurrence is the
/// first failing run of the current streak, so repeated failing runs are one occurrence until the family passes.
pub fn failed_tests(g: &GenCtx) -> Vec<Candidate> {
    let records = crate::verification::product::latest_records(g.p);
    // family -> (latest failing record, origin of the streak, latest entry); families whose latest run passed are done
    let mut state: BTreeMap<String, (Option<(String, String, Value)>, Option<String>, bool)> =
        BTreeMap::new();
    for r in &records {
        let rid = r["id"].as_str().unwrap_or("").to_string();
        let at = r["run_at"].as_str().unwrap_or("").to_string();
        let Some(fams) = r["families"].as_object() else {
            continue;
        };
        for (fam, e) in fams {
            let failed = e["status"].as_str() == Some("failed");
            let st = state.entry(fam.clone()).or_insert((None, None, false));
            if st.2 {
                continue; // the streak ended (an older run of the family passed, or it was decided)
            }
            match (&st.0, failed) {
                (None, true) => {
                    st.0 = Some((rid.clone(), at.clone(), e.clone()));
                    st.1 = Some(rid.clone());
                }
                (None, false) => st.2 = true,
                (Some(_), true) => st.1 = Some(rid.clone()),
                (Some(_), false) => st.2 = true,
            }
        }
    }
    let (class, _, default_paths, _) = g.cfg.source("failed-tests");
    let _ = class;
    let mut out = vec![];
    for (fam, (latest, origin, _)) in state {
        let Some((rid, at, e)) = latest else { continue };
        let origin = origin.unwrap_or_else(|| rid.clone());
        let covers: Vec<String> = e["covers"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default();
        let paths = if covers.is_empty() || covers.iter().any(|c| c == "**") {
            default_paths.clone()
        } else {
            let mut v = covers.clone();
            v.extend(["tests/**".to_string(), "spec/**".to_string()]);
            v
        };
        out.push(Candidate {
            source: "failed-tests".into(),
            subject: fam.clone(),
            occurrence: origin.clone(),
            evidence_at: at.clone(),
            records: g.linkable(&[rid.clone()]),
            title: format!("Repair failing product test family '{fam}' ({rid})"),
            objective: format!(
                "The product test family '{fam}' fails in its latest recorded run {rid} (failing since {origin}; exit {}; command {}). Find the cause and repair the code or the test so the family passes, then record a passing run (`gov verify product`); the failing run is governed evidence, not a report claim. stderr tail: {}",
                e["exit"], e["command"], clip(e["stderr_tail"].as_str().unwrap_or(""), 400)
            ),
            paths,
            detail: json!({"family": fam, "record": rid, "streak_origin": origin, "exit": e["exit"], "command": e["command"], "covers": covers, "stdout_tail": e["stdout_tail"], "stderr_tail": e["stderr_tail"]}),
            ..Default::default()
        });
    }
    out
}

/// **Audit findings, security findings and each health failure** (Contract v3:575, :582; AC-5; O5): every check of
/// the health state (governance-suite families and doctor checks) failing at or above the policy severity, one piece
/// of remediation work per condition (a doctor check and the family reporting the same condition are one), with the
/// findings of the latest honoured governance-suite record.
pub fn health_failures(g: &GenCtx) -> Vec<Candidate> {
    let st = crate::scheduler::store::load_state(g.p);
    let Some(checks) = st["checks"].as_object() else {
        return vec![];
    };
    let threshold = crate::scheduler::catalogue::rank(&g.cfg.severity_threshold());
    let excluded = g.cfg.list("excluded_checks");
    let security = g.cfg.list("security_checks");
    let memory = g.cfg.list("memory_checks");
    // the latest honoured governance-suite record, for the findings behind each failing family
    let mut suite: Vec<&Record> = g
        .store
        .of_type("audit")
        .into_iter()
        .filter(|r| {
            r.get("scope") == "governance-suite" && crate::t2::verify_record(r).is_verified()
        })
        .collect();
    suite.sort_by_key(|r| (r.get("run_at"), r.id()));
    let latest_suite = suite.last().copied();
    // condition -> (member checks, max severity, latest at, findings)
    let mut groups: BTreeMap<String, (Vec<String>, String, String, Vec<Value>)> = BTreeMap::new();
    for (id, e) in checks {
        if e["ok"].as_bool().unwrap_or(true) || excluded.contains(id) {
            continue;
        }
        let sev = e["max_severity"].as_str().unwrap_or("none").to_string();
        if crate::scheduler::catalogue::rank(&sev) < threshold {
            continue;
        }
        let canonical = g.cfg.canonical_check(id);
        if excluded.contains(&canonical) {
            continue;
        }
        let entry = groups.entry(canonical.clone()).or_insert((
            vec![],
            "none".into(),
            String::new(),
            vec![],
        ));
        entry.0.push(id.clone());
        if crate::scheduler::catalogue::rank(&sev) > crate::scheduler::catalogue::rank(&entry.1) {
            entry.1 = sev.clone();
        }
        let at = e["at"].as_str().unwrap_or("").to_string();
        if at > entry.2 {
            entry.2 = at;
        }
        for f in e["blocking_findings"]
            .as_array()
            .cloned()
            .unwrap_or_default()
        {
            entry.3.push(f);
        }
        if let Some(s) = latest_suite {
            for f in s.data["findings"].as_array().cloned().unwrap_or_default() {
                if f["family"].as_str() == Some(id.as_str())
                    && crate::scheduler::catalogue::rank(f["severity"].as_str().unwrap_or("low"))
                        >= threshold
                {
                    entry.3.push(f);
                }
            }
        }
    }
    if groups.is_empty() {
        return vec![];
    }
    // only a failure that is still current is work: a failing result whose check inputs have changed since it was
    // recorded (the condition may have been repaired, e.g. a kernel re-verified) waits for its re-evaluation
    let stale: BTreeSet<String> = crate::scheduler::status(g.p)
        .ok()
        .and_then(|s| s["stale_checks"].as_array().cloned())
        .unwrap_or_default()
        .into_iter()
        .filter_map(|x| x.as_str().map(|s| s.to_string()))
        .collect();
    // checks whose findings name the same path report one condition (e.g. a secret in a product file reported by
    // the path-map and the secrets checks): one remediation, which remedies every one of them
    let mut conds: Vec<(String, Vec<String>, String, String, Vec<Value>)> = groups
        .into_iter()
        .map(|(c, (m, sev, at, f))| {
            let m: Vec<String> = m.into_iter().filter(|x| !stale.contains(x)).collect();
            (c, m, sev, at, f)
        })
        .filter(|(_, m, _, _, _)| !m.is_empty())
        .collect();
    let paths_of = |f: &[Value]| -> BTreeSet<String> {
        f.iter()
            .filter_map(|x| x["path"].as_str().map(|s| s.to_string()))
            .filter(|s| !s.is_empty() && !g.generated_tasks.contains(s))
            .collect()
    };
    let mut merged = true;
    while merged {
        merged = false;
        'outer: for i in 0..conds.len() {
            for j in (i + 1)..conds.len() {
                let (a, b) = (paths_of(&conds[i].4), paths_of(&conds[j].4));
                if !a.is_empty() && a.intersection(&b).next().is_some() {
                    let other = conds.remove(j);
                    let c = &mut conds[i];
                    if other.0 < c.0 {
                        c.0 = other.0.clone();
                    }
                    for m in other.1 {
                        if !c.1.contains(&m) {
                            c.1.push(m);
                        }
                    }
                    if crate::scheduler::catalogue::rank(&other.2)
                        > crate::scheduler::catalogue::rank(&c.2)
                    {
                        c.2 = other.2;
                    }
                    if other.3 > c.3 {
                        c.3 = other.3;
                    }
                    c.4.extend(other.4);
                    merged = true;
                    break 'outer;
                }
            }
        }
    }
    let markers: Vec<String> = g
        .cfg
        .list("security_markers")
        .into_iter()
        .map(|m| m.to_lowercase())
        .collect();
    let mut out = vec![];
    for (canonical, mut members, sev, at, findings) in conds {
        members.sort();
        let total = findings.len();
        let findings: Vec<Value> = findings
            .into_iter()
            .filter(|f| !g.about_generated_work(f))
            .collect();
        if total > 0 && findings.is_empty() {
            continue; // every finding is about generated work itself: no loop
        }
        let mut seen = BTreeSet::new();
        let findings: Vec<Value> = findings
            .into_iter()
            .filter(|f| seen.insert((f["message"].to_string(), f["path"].to_string())))
            .collect();
        let is_security = members
            .iter()
            .chain(std::iter::once(&canonical))
            .any(|m| security.contains(m))
            || findings.iter().any(|f| {
                let msg = f["message"].as_str().unwrap_or("").to_lowercase();
                markers.iter().any(|m| msg.contains(m.as_str()))
            });
        let is_memory = members
            .iter()
            .chain(std::iter::once(&canonical))
            .any(|m| memory.contains(m));
        let is_doctor = members.iter().all(|m| m.starts_with('D') && m.len() == 4);
        let source = if is_security {
            "security-finding"
        } else if is_memory {
            "memory-health"
        } else if is_doctor {
            "health-failure"
        } else {
            "audit-finding"
        };
        // what failed, independent of volatile counts: the finding messages and paths without digits
        let mut sig: Vec<String> = findings
            .iter()
            .map(|f| {
                format!(
                    "{}|{}",
                    f["message"]
                        .as_str()
                        .unwrap_or("")
                        .chars()
                        .filter(|c| !c.is_ascii_digit())
                        .collect::<String>(),
                    f["path"].as_str().unwrap_or("")
                )
            })
            .collect();
        sig.sort();
        sig.dedup();
        if sig.is_empty() {
            sig.push(format!("{canonical}:{sev}"));
        }
        let finding_paths: Vec<String> = findings
            .iter()
            .filter_map(|f| f["path"].as_str().map(|s| s.to_string()))
            .filter(|s| !s.is_empty())
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect();
        let (_, _, default_paths, _) = g.cfg.source(source);
        let paths = if is_security && !finding_paths.is_empty() {
            let mut v = finding_paths.clone();
            v.push("spec/**".into());
            v
        } else {
            default_paths
        };
        let msgs: Vec<String> = findings
            .iter()
            .take(5)
            .map(|f| {
                format!(
                    "{} {}{}",
                    f["severity"].as_str().unwrap_or(&sev),
                    clip(f["message"].as_str().unwrap_or(""), 200),
                    f["path"]
                        .as_str()
                        .map(|p| format!(" ({p})"))
                        .unwrap_or_default()
                )
            })
            .collect();
        let record = latest_suite
            .filter(|s| {
                s.data["findings"]
                    .as_array()
                    .map(|a| {
                        a.iter().any(|f| {
                            members
                                .iter()
                                .any(|m| f["family"].as_str() == Some(m.as_str()))
                        })
                    })
                    .unwrap_or(false)
            })
            .map(|s| s.id());
        let what = match source {
            "security-finding" => "security finding",
            "health-failure" => "health failure",
            "memory-health" => "knowledge-fabric health failure",
            _ => "audit finding",
        };
        out.push(Candidate {
            source: source.into(),
            subject: canonical.clone(),
            occurrence: digest(&sig),
            evidence_at: at.clone(),
            records: g.linkable(&record.iter().cloned().collect::<Vec<_>>()),
            title: format!("Remediate {what}: {canonical} ({sev})"),
            objective: format!(
                "Health check {canonical}{} fails ({sev}): {}. Find the cause and repair it through its governed route (a CIT for governed state, a task for product or test changes); the remediation is verified by the check passing when it is re-evaluated (`gov health run`, `gov audit`, `gov doctor`), not by this task's report.",
                if members.len() > 1 || members.first() != Some(&canonical) { format!(" (reported by {})", members.join(", ")) } else { String::new() },
                if msgs.is_empty() { "see the health state (`gov health status`)".to_string() } else { msgs.join("; ") }
            ),
            paths,
            remedies: {
                let mut r = members.clone();
                if !r.contains(&canonical) {
                    r.push(canonical.clone());
                }
                r
            },
            detail: json!({"check": canonical, "members": members, "severity": sev, "findings": findings.iter().take(20).cloned().collect::<Vec<_>>(), "governance_suite_record": record, "health_state_at": at}),
            ..Default::default()
        });
    }
    out
}

/// **Research discoveries** (Contract v3:576): what a worker's return (`handoff return`) or a sealed close report
/// says it discovered, left unresolved or proposes to decide. One follow-up per item; an item reported both in the
/// return and in the close report of the same task is one piece of work.
pub fn discoveries(g: &GenCtx) -> Vec<Candidate> {
    let mut out = vec![];
    let mut push = |task: &str, record: &str, at: &str, v: &Value| {
        for (field, source, what) in [
            ("discoveries", "research-discovery", "discovery"),
            ("unresolved", "research-discovery", "unresolved item"),
            (
                "proposed_decisions",
                "proposed-decision",
                "proposed decision",
            ),
        ] {
            for item in v[field].as_array().cloned().unwrap_or_default() {
                let text = text_of(&item);
                if g.cfg.trivial(&text) {
                    continue;
                }
                let h = digest(&[field.to_string(), text.trim().to_lowercase()]);
                let scope = if task.is_empty() { record } else { task };
                let subject = format!("{scope}#{field}#{h}");
                let objective = match field {
                    "proposed_decisions" => format!("Prepare the decision proposed by {record}{}: '{}'. Assemble the decision package (options, impact, reversibility, recommendation) and raise it as a Human Decision Gate or, within policy, resolve it with its rationale; link the result to this task.", if task.is_empty() { String::new() } else { format!(" (task {task})") }, clip(&text, 400)),
                    _ => format!("Follow up the {what} reported by {record}{}: '{}'. Decide what governed work it calls for — a requirement or scenario, a CIT, a decision gate, research or a task — create and link it (derived from this task), or record why none is needed.", if task.is_empty() { String::new() } else { format!(" (task {task})") }, clip(&text, 400)),
                };
                out.push(Candidate {
                    source: source.into(),
                    subject: subject.clone(),
                    occurrence: h.clone(),
                    evidence_at: at.to_string(),
                    records: vec![record.to_string()],
                    title: format!("Follow up {what} from {scope}: {}", clip(&text, 80)),
                    objective,
                    detail: json!({"field": field, "item": item, "reported_by": record, "task": task}),
                    ..Default::default()
                });
            }
        }
    };
    for h in g.store.of_type("handoff") {
        let ret = &h.data["return"];
        if !ret.is_object() {
            continue;
        }
        let at = h.get("returned_at");
        push(&h.get("task"), &h.id(), &at, ret);
    }
    for r in g.store.of_type("report") {
        // only the OS-written close report counts (a hand-written report states nothing the OS recorded)
        if !crate::t2::verify_record(r).is_verified() {
            continue;
        }
        let at = r.data["mutation_evidence"]["closed_at"]
            .as_str()
            .map(|s| s.to_string())
            .unwrap_or_else(|| r.get("created"));
        push(&r.get("task"), &r.id(), &at, &r.data);
    }
    for c in out.iter_mut() {
        c.records = g.linkable(&c.records);
    }
    out
}

/// **Human decisions** (Contract v3:577): a T2-verified decision derived from a human's answer to a gate an agent
/// raised. A gate the OS raised for one of its own operations (a CIT, a budget, a profile, a promotion, an update) is
/// applied by that operation, and an authorising answer to a gate that governs tasks releases those tasks — they carry
/// the decision. Otherwise the decision is carried out by generated work; a declining answer that stops governed work
/// generates the work of replanning it.
pub fn human_decisions(g: &GenCtx) -> Vec<Candidate> {
    let mut out = vec![];
    for d in g.store.of_type("decision") {
        let human = d
            .data
            .get("human_approved")
            .and_then(|v| v.as_bool())
            .unwrap_or(false)
            || d.get("approved_by_kind") == "human";
        if !human || !crate::t2::verify_record(d).is_verified() {
            continue;
        }
        if matches!(
            d.status().as_str(),
            "SUPERSEDED" | "REJECTED" | "HISTORICAL" | "RETIRED"
        ) {
            continue;
        }
        let Some(gate_id) = d
            .list("derived_from")
            .into_iter()
            .find(|x| x.starts_with("HDG-"))
        else {
            continue;
        };
        let Some(gate) = g.store.get(&gate_id) else {
            continue;
        };
        if gate.data["raised_by"]["kind"].as_str() == Some("system")
            || !gate.get("cit").is_empty()
            || !d.get("cit").is_empty()
        {
            continue; // the OS operation that raised the gate applies its answer
        }
        let mut governed: Vec<String> = gate.list("blocks_tasks");
        for t in g.store.of_type("task") {
            if t.get("human_gate") == gate_id && !governed.contains(&t.id()) {
                governed.push(t.id());
            }
        }
        let declined = d
            .data
            .get("declined")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        if !declined && !governed.is_empty() {
            continue; // the released work carries the decision
        }
        let option = d.get("chosen_option");
        let option_text = gate.data["options"]
            .as_array()
            .and_then(|a| a.iter().find(|o| o["id"].as_str() == Some(option.as_str())))
            .map(|o| text_of(o))
            .unwrap_or_default();
        let question = gate.get("question");
        let (title, objective, affects) = if declined && !governed.is_empty() {
            (
                format!("Replan the work stopped by decision {} ({gate_id})", d.id()),
                format!("The human answered {gate_id} ('{}') with option {option}{}, which does not authorise the work it governs ({}). Replan it: cancel it, rework or re-scope it within the decision, or raise a new gate with a changed proposal.", clip(&question, 200), if option_text.is_empty() { String::new() } else { format!(" ({})", clip(&option_text, 120)) }, governed.join(", ")),
                governed.clone(),
            )
        } else {
            (
                format!("Carry out human decision {} ({gate_id}, option {option})", d.id()),
                format!("The human decided {gate_id} ('{}'): option {option}{}. Carry the decision out in the governed plan — update or create the requirements, decisions, CITs and tasks it requires (derived from {}) — or record why it requires no further work.", clip(&question, 200), if option_text.is_empty() { String::new() } else { format!(" — {}", clip(&option_text, 200)) }, d.id()),
                vec![],
            )
        };
        out.push(Candidate {
            source: "human-decision".into(),
            subject: d.id(),
            occurrence: d.id(),
            evidence_at: d
                .data
                .get("approved_at")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string())
                .unwrap_or_else(|| d.get("created")),
            records: g.linkable(&[d.id()]),
            title,
            objective,
            affects,
            detail: json!({"decision": d.id(), "gate": gate_id, "option": option, "declined": declined, "governed_tasks": governed}),
            ..Default::default()
        });
    }
    out
}

/// **CIT effects** (Contract v3:578, :1134 "revalidation/rework tasks are generated"): completed work an upstream
/// change marked `revalidation.required` for which no revalidation task exists — propagation generates it when the
/// acting role may create tasks and marks it pending otherwise; this completes it. Open dependents are their own
/// rework (marked `retest_required`; they close only with re-test evidence).
pub fn cit_effects(g: &GenCtx) -> Vec<Candidate> {
    let revalidating: BTreeSet<String> = g
        .store
        .of_type("task")
        .into_iter()
        .map(|t| t.get("revalidates"))
        .filter(|x| !x.is_empty())
        .collect();
    let mut out = vec![];
    for t in g.store.of_type("task") {
        if t.get("task_status") != "DONE"
            || t.data["revalidation"]["required"].as_bool() != Some(true)
            || revalidating.contains(&t.id())
        {
            continue;
        }
        let tid = t.id();
        let changed: Vec<String> = t.data["staleness"]["inputs_changed"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(|x| x["id"].as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default();
        let mut fields = json!({"revalidates": tid, "revalidation_of": {"task": tid, "report": t.get("closed_by_report"), "cause": t.data["revalidation"]["cause"], "inputs_changed": t.data["staleness"]["inputs_changed"]}});
        for k in [
            "feature",
            "requirements",
            "decisions",
            "scenarios",
            "acceptance_tests",
            "interfaces",
            "architecture",
            "required_data",
            "required_inputs",
            "optional_inputs",
            "allowed_paths",
            "forbidden_paths",
        ] {
            if let Some(v) = t.data.get(k).filter(|v| !v.is_null()) {
                fields[k] = v.clone();
            }
        }
        let paths = t.list("allowed_paths");
        out.push(Candidate {
            source: "cit-effect".into(),
            subject: tid.clone(),
            occurrence: tid.clone(),
            evidence_at: t.data["revalidation"]["at"]
                .as_str()
                .unwrap_or("")
                .to_string(),
            records: g.linkable(&[t.get("closed_by_report")]),
            title: format!("Revalidate {tid} after its inputs changed"),
            objective: format!("Revalidate the completed work of {tid} ({}) against its changed inputs {}: re-run its acceptance evidence at the current input versions, rework what no longer holds, and close with a consumption receipt at the current hashes (its close resolves {tid}'s revalidation).", t.title(), changed.join(", ")),
            paths,
            fields,
            detail: json!({"revalidates": tid, "inputs_changed": changed, "cause": t.data["revalidation"]["cause"]}),
            ..Default::default()
        });
    }
    out
}

/// **Lessons** (Contract v3:579): every lesson record (candidate or active) is acted on — applied to this project
/// through its governed route, proposed upstream when it is generic, or recorded as needing no change.
pub fn lessons(g: &GenCtx) -> Vec<Candidate> {
    let mut out = vec![];
    for l in g.store.of_type("lesson") {
        if matches!(
            l.status().as_str(),
            "SUPERSEDED" | "REJECTED" | "HISTORICAL" | "RETIRED" | "LEGACY"
        ) {
            continue;
        }
        let text = [l.get("problem_statement"), l.get("summary"), l.title()]
            .into_iter()
            .find(|s| !s.trim().is_empty())
            .unwrap_or_default();
        let scope = l.get("scope");
        out.push(Candidate {
            source: "lesson".into(),
            subject: l.id(),
            occurrence: l.id(),
            evidence_at: l.get("created"),
            records: g.linkable(&[l.id()]),
            title: format!("Act on lesson {}: {}", l.id(), clip(&text, 80)),
            objective: format!("Lesson {} ({} scope, category {}, evidence {}): '{}'. Decide what it changes in how this project works — a skill, a policy overlay (through a CIT), a process or a test — and make that change through its governed route; propose it upstream when it is generic (`gov upstream prepare {}` once it is scoped for export); or record why it needs no change.", l.id(), if scope.is_empty() { "PROJECT".into() } else { scope }, l.get("category"), l.get("evidence_strength"), clip(&text, 400), l.id()),
            detail: json!({"lesson": l.id(), "suggested_change": l.data.get("suggested_change"), "sources": l.data.get("sources")}),
            ..Default::default()
        });
    }
    out
}

/// **Missing tools and skills** (Contract v3:580): open work requiring a tool or skill that does not resolve. One
/// task per missing capability, which `blocks` every task that needs it (more work needing it later is added).
pub fn missing_capabilities(g: &GenCtx) -> Vec<Candidate> {
    let r = crate::orchestration::dag::InputResolver::new(g.p, g.store);
    // (kind, id) -> (needing tasks, earliest created)
    let mut need: BTreeMap<(&'static str, String), (Vec<String>, String)> = BTreeMap::new();
    for t in g.store.of_type("task") {
        if matches!(t.get("task_status").as_str(), "DONE" | "CANCELLED") || source_of(t).is_some() {
            continue;
        }
        for (kind, field) in [
            ("missing-tool", "required_tools"),
            ("missing-skill", "required_skills"),
        ] {
            for id in t.list(field) {
                let missing = if kind == "missing-tool" {
                    r.tool(&id).is_err()
                } else {
                    r.skill(&id).is_err()
                };
                if missing {
                    let e = need
                        .entry((kind, id.clone()))
                        .or_insert((vec![], t.get("created")));
                    e.0.push(t.id());
                    let c = t.get("created");
                    if !c.is_empty() && (e.1.is_empty() || c < e.1) {
                        e.1 = c;
                    }
                }
            }
        }
    }
    let mut out = vec![];
    for ((kind, id), (tasks, at)) in need {
        let what = if kind == "missing-tool" {
            "tool"
        } else {
            "skill"
        };
        let how = if kind == "missing-tool" {
            "register an existing tool (`gov tools install <descriptor>`, the capability registry) or build it as governed tooling"
        } else {
            "add the skill to the project's governed skills (its method and validation scenarios), or change the tasks to use an existing skill"
        };
        out.push(Candidate {
            source: kind.into(),
            subject: id.clone(),
            occurrence: id.clone(),
            evidence_at: if at.is_empty() { now_iso() } else { at },
            records: vec![],
            title: format!("Provide the missing {what} '{id}'"),
            objective: format!("Tasks {} require the {what} '{id}', which does not resolve. Provide it: {how}. The tasks it blocks become runnable once it resolves.", tasks.join(", ")),
            blocks: tasks.clone(),
            detail: json!({"capability": what, "id": id, "needed_by": tasks}),
            ..Default::default()
        });
    }
    out
}

/// **Retrieval failures and other failure memory** (Contract v3:581; framework §11.8, §18): every failure record
/// whose follow-up is still open. The task is linked back from the record (`follow_up.task`).
pub fn failures(g: &GenCtx) -> Vec<Candidate> {
    let open: BTreeSet<String> = crate::memory::failures::open_failures(g.p)
        .into_iter()
        .filter_map(|f| f["id"].as_str().map(|s| s.to_string()))
        .collect();
    let mut out = vec![];
    for (path, v) in crate::memory::failures::list(g.p) {
        let id = v["id"].as_str().unwrap_or("").to_string();
        if !open.contains(&id) {
            continue;
        }
        let kind = v["failure_kind"].as_str().unwrap_or("bug").to_string();
        let source = match kind.as_str() {
            "retrieval-miss" => "retrieval-failure",
            "tool-failure" => "tool-failure",
            "regression" if v["subject"]["performance"].as_bool() == Some(true) => {
                "performance-regression"
            }
            _ => "failure",
        };
        let actions: Vec<String> = v["follow_up"]["required_actions"]
            .as_array()
            .map(|a| a.iter().map(text_of).collect())
            .unwrap_or_default();
        out.push(Candidate {
            source: source.into(),
            subject: id.clone(),
            occurrence: v["signature"].as_str().unwrap_or(&id).to_string(),
            evidence_at: v["occurred_at"].as_str().unwrap_or("").to_string(),
            records: g.linkable(&[id.clone()]),
            title: format!("Follow up {kind} {id}: {}", clip(v["title"].as_str().unwrap_or(""), 80)),
            objective: format!("Failure {id} ({kind}, {path}): {}. Establish the root cause and repair it{}; framework §18: a retrieval failure is fixed at its cause and gains a held-out query that would have caught it.", clip(v["summary"].as_str().unwrap_or(""), 400), if actions.is_empty() { String::new() } else { format!(" — required: {}", actions.join("; ")) }),
            failure: Some(id.clone()),
            detail: json!({"failure": id, "failure_kind": kind, "path": path, "subject": v["subject"], "root_cause_candidates": v["root_cause_candidates"]}),
            ..Default::default()
        });
    }
    out
}

/// **Performance regressions** (Contract v3:583): a product measurement reported to the OS (`gov telemetry emit`) that
/// exceeds its declared baseline — or, for a performance-namespaced metric, the median of its earlier samples — by the
/// policy factor and margin. Each regression becomes a durable `regression` failure record (the telemetry log is
/// derived state), which [`failures`] turns into linked `performance` work. Telemetry of the Governance OS itself is
/// excluded (its SLOs are Gate U).
pub fn detect_performance_regressions(g: &GenCtx, record: bool) -> Vec<Value> {
    let cfg = &g.cfg;
    let factor = cfg.perf("factor").as_f64().unwrap_or(1.5);
    let min_delta = cfg.perf("min_delta_ms").as_f64().unwrap_or(10.0);
    let min_samples = cfg.perf("min_samples").as_u64().unwrap_or(5) as usize;
    let strs = |k: &str| -> Vec<String> {
        cfg.perf(k)
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default()
    };
    let (measures, baselines, own, history_ns) = (
        strs("measures"),
        strs("baselines"),
        strs("own_namespaces"),
        strs("history_namespaces"),
    );
    let mut history: BTreeMap<(String, String), Vec<f64>> = BTreeMap::new();
    let mut found = vec![];
    for ev in crate::observability::events(g.p) {
        let name = ev["name"].as_str().unwrap_or("").to_string();
        if name.is_empty() || own.iter().any(|o| name.starts_with(o.as_str())) {
            continue;
        }
        let a = &ev["attributes"];
        let Some((measure, value)) = measures
            .iter()
            .find_map(|m| a[m.as_str()].as_f64().map(|v| (m.clone(), v)))
        else {
            continue;
        };
        let declared = baselines.iter().find_map(|b| a[b.as_str()].as_f64());
        let hist = history.entry((name.clone(), measure.clone())).or_default();
        let baseline = match declared {
            Some(b) => Some((b, "declared baseline")),
            None if history_ns.iter().any(|h| name.starts_with(h.as_str()))
                && hist.len() >= min_samples =>
            {
                let mut v = hist.clone();
                v.sort_by(|x, y| x.partial_cmp(y).unwrap_or(std::cmp::Ordering::Equal));
                Some((v[v.len() / 2], "median of earlier samples"))
            }
            None => None,
        };
        hist.push(value);
        let Some((base, basis)) = baseline else {
            continue;
        };
        if value > base * factor && value - base >= min_delta {
            found.push(json!({"metric": name, "measure": measure, "value": value, "baseline": base, "basis": basis,
                "factor": factor, "at": ev["timestamp"], "session": ev["session"], "attributes": a}));
        }
    }
    // one durable failure record per regression signature (metric, measure, baseline)
    if record {
        for r in &found {
            let ev = crate::memory::failures::FailureEvent {
                kind: "regression".into(),
                signature_basis: json!({"metric": r["metric"], "measure": r["measure"], "baseline": r["baseline"]}),
                title: format!("Performance regression: {} {} {} vs baseline {}", r["metric"].as_str().unwrap_or("?"), r["measure"].as_str().unwrap_or("?"), r["value"], r["baseline"]),
                summary: format!("{} measured {} = {} against a {} of {} (policy: more than {}x and at least {} ms worse)", r["metric"].as_str().unwrap_or("?"), r["measure"].as_str().unwrap_or("?"), r["value"], r["basis"].as_str().unwrap_or(""), r["baseline"], factor, min_delta),
                subject: json!({"performance": true, "metric": r["metric"], "measure": r["measure"], "value": r["value"], "baseline": r["baseline"], "basis": r["basis"], "observed_at": r["at"]}),
                root_cause_candidates: vec!["a change since the baseline was measured".into(), "environment or load".into()],
                required_actions: vec!["reproduce the measurement".into(), "find the change that caused it".into(), "repair it or record an accepted new baseline through a decision".into()],
                operation: "work generation (telemetry)".into(),
                detection: "automatic".into(),
            };
            // `true`: a current index is kept current for the new record (a stale one is left as it was)
            let _ = crate::memory::failures::record(g.p, ev, true);
        }
    }
    found
}

/// Every candidate of every source, in source order, with each source's errors isolated.
pub fn candidates(g: &GenCtx) -> Vec<Candidate> {
    let mut v = vec![];
    v.extend(failed_tests(g));
    v.extend(health_failures(g));
    v.extend(discoveries(g));
    v.extend(human_decisions(g));
    v.extend(cit_effects(g));
    v.extend(lessons(g));
    v.extend(missing_capabilities(g));
    v.extend(failures(g));
    v
}

// ------------------------------------------------------------------------------------------------ reconciliation

/// How [`reconcile`] runs.
#[derive(Debug, Clone)]
pub struct Options {
    /// The operation that ran it (recorded as `generation.detected_by`).
    pub trigger: String,
    /// Report what would be generated; write nothing.
    pub dry_run: bool,
}

impl Options {
    pub fn triggered_by(trigger: &str) -> Options {
        Options {
            trigger: trigger.to_string(),
            dry_run: false,
        }
    }
}

/// **Generate the governed work every source calls for** (idempotent; see the module documentation). Returns what was
/// created, augmented and skipped (with why), the adopted work, and why nothing was written when writes are refused.
pub fn reconcile(p: &Project, o: &Options) -> Result<Value> {
    if !p.is_installed() {
        return Ok(json!({"skipped": "no Governance OS installation at this root"}));
    }
    if crate::scheduler::sandbox::inside_sandbox() {
        return Ok(json!({"skipped": "inside a health-check sandbox (a copy is not the project)"}));
    }
    if !o.dry_run {
        RECONCILED.store(true, Ordering::SeqCst);
    }
    let writable = if o.dry_run {
        Ok(())
    } else {
        control::guard_write(p, "work generation")
    };
    // the performance detector records durable failure memory first (it is itself a governed write)
    {
        let store = RecordStore::load(&p.root);
        let g = GenCtx::new(p, &store);
        let _ = detect_performance_regressions(&g, !o.dry_run && writable.is_ok());
    }
    let store = RecordStore::load(&p.root);
    let g = GenCtx::new(p, &store);
    let cands = candidates(&g);
    let mut ex = existing(&store);
    // like every record writer that keeps the derived index current (failure memory), generation refreshes it only
    // when it was current before: a stale or re-pinned index stays exactly as stale as it was (an incremental build
    // would otherwise re-embed under new pins as a side effect, and a stale index is its own finding)
    let mut index_was_fresh: Option<bool> = None;
    let mut created = vec![];
    let mut augmented = vec![];
    let mut skipped: BTreeMap<String, Vec<Value>> = BTreeMap::new();
    let mut pending = vec![];
    let mut errors = vec![];
    for c in &cands {
        let d = decide(c, &ex);
        match d {
            Decision::Skip { reason, task } => {
                skipped
                    .entry(reason)
                    .or_default()
                    .push(json!({"source": c.source, "subject": c.subject, "task": task}));
            }
            Decision::Augment { task, add_blocks } => {
                if o.dry_run || writable.is_err() {
                    pending.push(json!({"augment": task, "blocks": add_blocks}));
                    continue;
                }
                index_was_fresh.get_or_insert_with(|| index_fresh(p));
                match augment(p, &task, &add_blocks) {
                    Ok(()) => {
                        augmented.push(json!({"task": task, "blocks_added": add_blocks, "source": c.source, "subject": c.subject}));
                        if let Some(e) = ex.iter_mut().find(|e| e.task == task) {
                            e.blocks.extend(add_blocks);
                        }
                    }
                    Err(e) => {
                        errors.push(json!({"task": task, "code": e.code, "message": e.message}))
                    }
                }
            }
            Decision::Create { key, recurrence } => {
                if o.dry_run || writable.is_err() {
                    pending.push(json!({"candidate": c.to_value(), "key": key}));
                    continue;
                }
                index_was_fresh.get_or_insert_with(|| index_fresh(p));
                match create_task(p, &g, c, &key, recurrence, &o.trigger) {
                    Ok(id) => {
                        created.push(json!({"task": id, "source": c.source, "subject": c.subject, "key": key, "records": c.records}));
                        ex.push(Generated {
                            task: id,
                            status: "READY".into(),
                            source: c.source.clone(),
                            subject: c.subject.clone(),
                            key: key.clone(),
                            base_key: c.key(),
                            closed_at: String::new(),
                            blocks: c.blocks.clone(),
                            adopted: false,
                        });
                    }
                    Err(e) => errors.push(json!({"source": c.source, "subject": c.subject, "code": e.code, "message": e.message})),
                }
            }
        }
    }
    // the new tasks are governed records: keep the derived index current for them, as every record writer does
    if (!created.is_empty() || !augmented.is_empty()) && index_was_fresh == Some(true) {
        let _ = crate::memory::indexer::rebuild(
            p,
            crate::memory::indexer::IndexOptions {
                incremental: true,
                ..Default::default()
            },
        );
    }
    let adopted: Vec<Value> = ex
        .iter()
        .filter(|e| e.adopted)
        .map(|e| json!({"task": e.task, "source": e.source, "subject": e.subject, "task_status": e.status}))
        .collect();
    let mut by_source: BTreeMap<String, usize> = BTreeMap::new();
    for c in &cands {
        *by_source.entry(c.source.clone()).or_insert(0) += 1;
    }
    let out = json!({
        "trigger": o.trigger, "dry_run": o.dry_run, "generator": GENERATOR,
        "candidates": cands.len(), "by_source": by_source,
        "created": created, "augmented": augmented,
        "skipped": skipped, "pending": pending, "errors": errors,
        "adopted": adopted,
        "not_generated": writable.err().map(|e| json!({"code": e.code, "message": e.message, "effect": "nothing was generated; the events remain and are generated from once writes are allowed"})),
    });
    if !o.dry_run && (!created_is_empty(&out) || !augmented_is_empty(&out)) {
        let _ = crate::observability::emit(
            p,
            "work.generation",
            json!({"trigger": o.trigger, "created": out["created"].as_array().map(|a| a.len()).unwrap_or(0), "augmented": out["augmented"].as_array().map(|a| a.len()).unwrap_or(0)}),
        );
    }
    Ok(out)
}

/// Is the derived index current (built, pins matching, nothing stale)?
fn index_fresh(p: &Project) -> bool {
    p.db_path().exists() && crate::memory::manifest::freshness(p).fresh
}

fn created_is_empty(v: &Value) -> bool {
    v["created"]
        .as_array()
        .map(|a| a.is_empty())
        .unwrap_or(true)
}
fn augmented_is_empty(v: &Value) -> bool {
    v["augmented"]
        .as_array()
        .map(|a| a.is_empty())
        .unwrap_or(true)
}

/// A compact view of a reconciliation for a command result: the tasks created and augmented, or why none were.
pub fn summary(report: &Value) -> Value {
    json!({"created": report["created"].as_array().map(|a| a.iter().map(|x| x["task"].clone()).collect::<Vec<_>>()).unwrap_or_default(),
           "augmented": report["augmented"].as_array().map(|a| a.iter().map(|x| x["task"].clone()).collect::<Vec<_>>()).unwrap_or_default(),
           "not_generated": report["not_generated"], "error": report["error"]})
}

fn create_task(
    p: &Project,
    g: &GenCtx,
    c: &Candidate,
    key: &str,
    recurrence: usize,
    trigger: &str,
) -> Result<String> {
    let (class, role, default_paths, contract) = g.cfg.source(&c.source);
    let mut f = if c.fields.is_object() {
        c.fields.clone()
    } else {
        json!({})
    };
    let paths = if c.paths.is_empty() {
        default_paths
    } else {
        c.paths.clone()
    };
    f["title"] = json!(c.title);
    f["objective"] = json!(c.objective);
    f["class"] = json!(class);
    f["task_status"] = json!("READY");
    if let Some(r) = role {
        f["role"] = json!(r);
    }
    if f.get("allowed_paths").is_none() {
        f["allowed_paths"] = json!(paths);
    }
    f["forbidden_paths"] = json!(["governance/kernel/**"]);
    let merges = !matches!(
        class.as_str(),
        "governance" | "discovery" | "decision-preparation" | "specification" | "validation"
    );
    f["production_merge_allowed"] = json!(merges);
    if !c.records.is_empty() {
        let mut d: Vec<String> = f
            .get("derived_from")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default();
        for r in &c.records {
            if !d.contains(r) {
                d.push(r.clone());
            }
        }
        f["derived_from"] = json!(d);
    }
    if !c.blocks.is_empty() {
        f["blocks"] = json!(c.blocks);
    }
    if !c.affects.is_empty() {
        f["relations"] = json!(c
            .affects
            .iter()
            .map(|t| json!({"type": "AFFECTS", "target": t, "note": format!("generated from {} {}", c.source, c.subject)}))
            .collect::<Vec<_>>());
    }
    if !c.remedies.is_empty() {
        f["remedies"] = json!(c.remedies);
    }
    f["generated_by"] = json!(GENERATOR);
    f["generation"] = json!({
        "source": c.source, "subject": c.subject, "key": key, "base_key": c.key(), "occurrence": c.occurrence,
        "recurrence": recurrence, "records": c.records, "failure": c.failure, "evidence_at": c.evidence_at,
        "detected_by": trigger, "detected_at": now_iso(), "contract": contract, "detail": c.detail,
    });
    let v = crate::orchestration::tasks::create_generated(p, f, trigger)?;
    let id = v["id"].as_str().unwrap_or("").to_string();
    if id.is_empty() {
        return Err(GovError::new(
            "GENERATION_FAILED",
            "the generated task has no id",
        ));
    }
    if let Some(fail) = &c.failure {
        crate::memory::failures::link_follow_up(p, fail, Some(&id), None)?;
    }
    Ok(id)
}

/// Add tasks a generated capability task unblocks to its `blocks` (more work needs the same missing tool or skill).
fn augment(p: &Project, task: &str, add: &[String]) -> Result<()> {
    control::guard_write(p, "work generation")?;
    let mut store = RecordStore::load(&p.root);
    let t = store
        .get_mut(task)
        .ok_or_else(|| GovError::new("TASK_NOT_FOUND", format!("{task} not found")))?;
    let mut b = t.list("blocks");
    for x in add {
        if !b.contains(x) {
            b.push(x.clone());
        }
    }
    t.set("blocks", json!(b));
    t.set("updated", json!(crate::util::today()));
    crate::records::save_record(&p.root, t)
}

/// **The post-command site** (`cli/src/main.rs::main`, after the command ran — whether it succeeded or failed, since
/// a failing command may have recorded its event, e.g. a failing product-test run): generate the work the command's
/// events call for, when the command is a governed **write** (its G0 classification) on an installed project, outside
/// a health sandbox, not lifecycle ingress or an emergency control, and not already reconciled by the operation
/// itself. Read-only commands never write. Never fails the command.
pub fn after_command(p: &Project, label: &str) -> Option<Value> {
    if RECONCILED.load(Ordering::SeqCst) || !p.is_installed() {
        return None;
    }
    if QUIET_AFTER
        .iter()
        .any(|q| label == *q || label.starts_with(&format!("{q} ")))
    {
        return None;
    }
    let g = control::command_guard(label)?;
    if g.effect != control::Effect::Write || matches!(g.scope, control::Scope::Outside(_)) {
        return None;
    }
    reconcile(p, &Options::triggered_by(label)).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gen(source: &str, subject: &str, key: &str, status: &str, closed_at: &str) -> Generated {
        Generated {
            task: format!("TASK-{subject}-{status}"),
            status: status.into(),
            source: source.into(),
            subject: subject.into(),
            key: key.into(),
            base_key: key.into(),
            closed_at: closed_at.into(),
            blocks: vec![],
            adopted: false,
        }
    }

    fn cand(source: &str, subject: &str, occurrence: &str, at: &str) -> Candidate {
        Candidate {
            source: source.into(),
            subject: subject.into(),
            occurrence: occurrence.into(),
            evidence_at: at.into(),
            ..Default::default()
        }
    }

    /// One task per occurrence, at most one open task per subject; a cancelled task declines its occurrence; after a
    /// completed task only newer evidence generates again, as a recurrence.
    #[test]
    fn generation_is_idempotent_per_occurrence_and_subject() {
        let c = cand(
            "audit-finding",
            "graph_integrity",
            "abc",
            "2026-09-19T10:00:00Z",
        );
        assert_eq!(
            decide(&c, &[]),
            Decision::Create {
                key: c.key(),
                recurrence: 0
            }
        );
        // an open task for the subject (even for another occurrence) suppresses a second
        let open = gen("audit-finding", "graph_integrity", "GEN-other", "READY", "");
        assert!(matches!(decide(&c, &[open]), Decision::Skip { .. }));
        // cancelled for this occurrence: declined
        let cancelled = gen(
            "audit-finding",
            "graph_integrity",
            &c.key(),
            "CANCELLED",
            "",
        );
        assert!(matches!(decide(&c, &[cancelled]), Decision::Skip { .. }));
        // a new occurrence after a cancellation of the old one generates
        let other = cand(
            "audit-finding",
            "graph_integrity",
            "def",
            "2026-09-19T11:00:00Z",
        );
        let cancelled_old = gen(
            "audit-finding",
            "graph_integrity",
            &c.key(),
            "CANCELLED",
            "",
        );
        assert!(matches!(
            decide(&other, &[cancelled_old]),
            Decision::Create { .. }
        ));
        // completed after the evidence: nothing (awaiting re-evaluation); evidence newer than the completion: again
        let done = gen(
            "audit-finding",
            "graph_integrity",
            &c.key(),
            "DONE",
            "2026-09-19T12:00:00Z",
        );
        assert!(matches!(decide(&c, &[done.clone()]), Decision::Skip { .. }));
        let later = cand(
            "audit-finding",
            "graph_integrity",
            "abc",
            "2026-09-19T13:00:00Z",
        );
        assert_eq!(
            decide(&later, &[done]),
            Decision::Create {
                key: format!("{}-r1", c.key()),
                recurrence: 1
            }
        );
        // a different subject is independent
        let x = cand(
            "audit-finding",
            "schema_invariants",
            "abc",
            "2026-09-19T10:00:00Z",
        );
        let open2 = gen("audit-finding", "graph_integrity", "GEN-other", "READY", "");
        assert!(matches!(decide(&x, &[open2]), Decision::Create { .. }));
    }

    /// More work needing a missing tool extends the open capability task's `blocks` instead of generating another.
    #[test]
    fn missing_capability_work_is_augmented_not_duplicated() {
        let mut c = cand("missing-tool", "TOOL-X", "TOOL-X", "2026-09-19");
        c.blocks = vec!["TASK-0002".into(), "TASK-0003".into()];
        let mut open = gen("missing-tool", "TOOL-X", &c.key(), "READY", "");
        open.blocks = vec!["TASK-0002".into()];
        assert_eq!(
            decide(&c, &[open]),
            Decision::Augment {
                task: "TASK-TOOL-X-READY".into(),
                add_blocks: vec!["TASK-0003".into()]
            }
        );
    }

    /// The kernel taxonomy names a class and a contract line for every source, and each designated role is a kernel
    /// role.
    #[test]
    fn the_taxonomy_declares_every_source() {
        let cfg = Config::embedded();
        let roles = include_str!("../../../framework/roles/ROLES.yaml");
        for s in [
            "failed-tests",
            "audit-finding",
            "health-failure",
            "security-finding",
            "memory-health",
            "research-discovery",
            "proposed-decision",
            "human-decision",
            "cit-effect",
            "lesson",
            "missing-tool",
            "missing-skill",
            "retrieval-failure",
            "tool-failure",
            "failure",
            "performance-regression",
        ] {
            let (class, role, _, contract) = cfg.source(s);
            assert!(
                !class.is_empty()
                    && (contract.contains("Contract") || contract.contains("framework")),
                "{s}"
            );
            if let Some(r) = role {
                assert!(
                    roles.contains(&format!("id: {r},")),
                    "{s}: role {r} is not a kernel role"
                );
            }
        }
        assert!(cfg.trivial("None"));
        assert!(cfg.trivial(" n/a. "));
        assert!(!cfg.trivial("u32 overflows at 4.2M cents"));
        assert_eq!(cfg.canonical_check("D015"), "graph_integrity");
    }
}
