"""W1-38 -- the template's rulesync hooks source: the time limit and the failed tool call (DEC-596).

DEC-596: "The template's rulesync hooks source (``template/.rulesync/hooks.jsonc``)
gets ``"timeout": 60`` on every guard hook entry, and the missing
PostToolUseFailure entry for the containment check. Without it an adopted
project runs no containment after a failed command, which ordinary work meets."

A project's harness settings are generated by rulesync from that source. The
cases read the source as the file it is, generate from it in a temporary
project (as the rest of this suite does), and run the commands the generated
settings register, with the input the harness gives after a failed tool call.
No real session is started; what that leaves open is in the README.

What a guard hook entry is, and what carrying the limit is: DEC-592, with the
words of ``tests/acceptance/W1-47/w1_47_hook_time_limit.py``.
"""

from __future__ import annotations

import copy
import json

import pytest

import w1_38_hooks_support as hooks
import w1_38_support as support

needs_rulesync = pytest.mark.needs_rulesync
limit = hooks.limit
LIMIT = f'"{limit.LIMIT_KEY}": {limit.LIMIT_S}'


@pytest.fixture(scope="module")
def programs():
    """The file names of the kernel template's hook programs."""
    return hooks.kernel_programs()


@pytest.fixture(scope="module")
def source():
    """The template's rulesync hooks source, as the object it holds."""
    return hooks.load_source()


@pytest.fixture()
def generated_settings(generated_project):
    """The harness settings rulesync generates from the template's sources in the temporary project."""
    return support.load_settings(generated_project)


@pytest.fixture()
def product(generated_project):
    """The generated project with a product's files and one engineer ticket in progress."""
    return hooks.add_product_work(generated_project)


@pytest.fixture()
def session_sandbox(tmp_path):
    """A stand-in home with the ``gov`` package installed, and a temporary folder, outside the project."""
    return hooks.make_session_sandbox(tmp_path / "session")


# ===================================================================
# The source: the limit on every guard hook entry (DEC-596, DEC-592)
# ===================================================================

def test_every_guard_hook_entry_of_the_source_carries_the_time_limit(source, programs):
    """Every entry of the source that runs a program of the kernel's hooks folder holds the whole number 60."""
    assert hooks.source_guard_entries(source, programs), (
        f"{hooks.SOURCE_REL} holds no guard hook entry, so the time limit would be held for nothing"
    )
    found = hooks.source_faults(source, programs)
    assert not found, (
        f"{hooks.SOURCE_REL}: a guard hook entry without `{LIMIT}` (DEC-596):\n  " + "\n  ".join(found)
    )


def _conforming(source, programs):
    """The template's source as an object in which every guard hook entry carries the limit."""
    changed = copy.deepcopy(source)
    for _where, entry in hooks.source_guard_entries(changed, programs):
        entry[limit.LIMIT_KEY] = limit.LIMIT_S
    return changed


def _set(value):
    def change(entry):
        entry[limit.LIMIT_KEY] = value
    return change


def _remove(entry):
    del entry[limit.LIMIT_KEY]


NOT_THE_LIMIT = {
    "absent": _remove,
    "as-a-fraction-60.0": _set(60.0),
    "as-a-string": _set("60"),
    "another-number": _set(30),
    "true": _set(True),
}


@pytest.mark.parametrize("kind", sorted(NOT_THE_LIMIT))
def test_one_source_entry_without_the_whole_number_60_is_found(source, programs, kind):
    """DEC-592: only the integer 60 counts. One entry of the source that holds something else is found, alone."""
    changed = _conforming(source, programs)
    assert hooks.source_faults(changed, programs) == [], "the source with the limit on every entry is faulted"
    NOT_THE_LIMIT[kind](hooks.source_guard_entries(changed, programs)[-1][1])
    found = hooks.source_faults(changed, programs)
    assert len(found) == 1, f"{kind}: one guard hook entry does not carry the limit, and the reading reports {found}"


def test_a_limit_written_as_a_fraction_in_the_source_file_is_found(source, programs):
    """The source is read as written: ``60.0`` in the file is not the whole number 60, although rulesync writes it
    to the generated settings as ``60`` (measured), where it can no longer be told apart."""
    changed = _conforming(source, programs)
    text = json.dumps(changed, indent=2)
    written = f'"{limit.LIMIT_KEY}": {limit.LIMIT_S}'
    assert written in text
    as_a_fraction = "// a comment, as the file's format allows\n" + text.replace(written, written + ".0", 1)
    found = hooks.source_faults(hooks.parse_source(as_a_fraction), programs)
    assert len(found) == 1, f"one entry was written with `{written}.0`, and the reading reports {found}"


def test_a_source_entry_that_runs_no_kernel_hook_is_left_as_it_is(source, programs):
    """A project's own hook in the source needs no limit, or its own."""
    changed = _conforming(source, programs)
    changed["hooks"]["notification"] = [
        {"type": "command", "command": "sh scripts/notify.sh"},
        {"type": "command", "command": "sh scripts/log.sh", limit.LIMIT_KEY: 5},
    ]
    assert hooks.source_faults(changed, programs) == [], "a hook entry that runs no kernel hook program was held to the limit"


# ===================================================================
# What rulesync generates from the source
# ===================================================================

class TestGeneratedGuardHooks:
    """The settings rulesync generates for Claude Code from the template's source, in a temporary project."""

    @needs_rulesync
    def test_every_guard_hook_entry_of_the_generated_settings_carries_the_time_limit(
        self, generated_settings, programs,
    ):
        """Every generated hook entry that runs a program of the kernel's hooks folder holds the number 60."""
        assert limit.guard_entries(generated_settings, programs), (
            f"{hooks.GENERATED_REL} registers no guard hook entry, so the time limit would be held for nothing"
        )
        found = limit.faults(generated_settings, programs)
        assert not found, (
            f"{hooks.GENERATED_REL}, generated from {hooks.SOURCE_REL}: a guard hook entry without `{LIMIT}` "
            f"(DEC-596):\n  " + "\n  ".join(found)
        )

    @needs_rulesync
    def test_the_generated_settings_run_the_containment_program_after_a_failed_bash_call(
        self, generated_settings, programs,
    ):
        """The harness's event for a failed tool call holds, for Bash, an entry that runs the program the kernel
        template's settings register for it."""
        program = hooks.containment_program(programs)
        commands = hooks.live_support.hook_commands(generated_settings, hooks.FAILED_CALL_EVENT, "Bash")
        assert any(program in command for command in commands), (
            f"{hooks.GENERATED_REL}, generated from {hooks.SOURCE_REL}, registers no {hooks.FAILED_CALL_EVENT} "
            f"command for Bash that runs {program}: it registers {commands}. An adopted project runs no "
            f"containment check after a failed command (DEC-596)"
        )

    @needs_rulesync
    @pytest.mark.parametrize("event", ("PreToolUse", "PostToolUse", "PostToolUseFailure"))
    def test_the_generated_settings_register_what_the_kernel_template_s_settings_register(
        self, generated_settings, programs, event,
    ):
        """Compared, under one event: for every hook entry that runs a kernel hook program, its matcher group's
        matcher (as written, or none), the program, and the value under ``timeout`` -- in the generated settings
        and in ``template/governance/kernel/settings.json``. The command lines around the program are not
        compared."""
        kernel = hooks.registered(hooks.kernel_settings(), programs, event)
        assert kernel, f"{hooks.KERNEL_SETTINGS_REL} registers no guard hook entry under {event}"
        generated = hooks.registered(generated_settings, programs, event)
        assert generated == kernel, (
            f"{event}: {hooks.GENERATED_REL}, generated from {hooks.SOURCE_REL}, registers (matcher, program, "
            f"limit) {generated}; {hooks.KERNEL_SETTINGS_REL} registers {kernel}"
        )

    def test_the_three_events_compared_are_the_kernel_template_s_guard_events(self, programs):
        """The comparison above leaves out no event under which the kernel template registers a guard hook."""
        assert sorted(hooks.guard_events(hooks.kernel_settings(), programs)) == sorted(
            ("PreToolUse", "PostToolUse", "PostToolUseFailure")
        )


# ===================================================================
# rulesync 24.0.0 passes both through (DEC-596, "it is verified")
# ===================================================================

class TestRulesyncPassesBothThrough:
    """A measurement of the registered rulesync, not of the template: the project's copy of the hooks source is
    given the limit on every entry and an entry under rulesync's name for a failed tool call, and the settings
    are generated again. It holds whatever the template's source says, and turns red if a later rulesync drops
    the limit or the event (the source could then not deliver DEC-596 without a hand edit)."""

    @needs_rulesync
    def test_a_limit_and_a_failed_tool_call_entry_of_the_source_reach_the_generated_settings(
        self, project, programs,
    ):
        path = project / hooks.PROJECT_SOURCE_REL
        changed = hooks.load_source(path, hooks.PROJECT_SOURCE_REL)
        after = [entry for where, entry in hooks.source_guard_entries(changed, programs)
                 if where.startswith(f"hooks.{hooks.RULESYNC_AFTER_CALL_KEY}[")]
        assert len(after) == 1, f"the source holds {len(after)} guard hook entries after a tool call; one is expected"
        changed["hooks"][hooks.RULESYNC_FAILED_CALL_KEY] = [{**copy.deepcopy(after[0]), "matcher": "Bash"}]
        for _where, entry in hooks.source_guard_entries(changed, programs):
            entry[limit.LIMIT_KEY] = limit.LIMIT_S
        hooks.write_source(path, changed)
        support.regenerate(project)

        settings = support.load_settings(project)
        assert limit.faults(settings, programs) == [], (
            f"rulesync {support.rulesync_version()} did not carry `{LIMIT}` of every source entry into "
            f"{hooks.GENERATED_REL}: {limit.faults(settings, programs)}"
        )
        program = hooks.program_of(after[0], programs)
        assert hooks.registered(settings, programs, hooks.FAILED_CALL_EVENT) == [("Bash", program, limit.LIMIT_S)], (
            f"rulesync {support.rulesync_version()} did not turn the source's `{hooks.RULESYNC_FAILED_CALL_KEY}` "
            f"entry into a {hooks.FAILED_CALL_EVENT} entry for Bash that runs {program}: "
            f"{json.dumps(settings.get('hooks', {}).get(hooks.FAILED_CALL_EVENT))}"
        )


# ===================================================================
# A session's failed command is followed by the containment check
# ===================================================================

class TestFailedCommandInAGeneratedProject:
    """One whole Bash call that fails, as a session makes it, through the commands the generated settings
    register: the PreToolUse commands for Bash, the command for real, then the commands registered for a failed
    tool call, with the input the harness gives then. The engineer works on a ticket whose paths are
    ``src/app/**`` and ``tests/unit/**``."""

    def _call(self, product, sandbox, command, changed):
        call = hooks.failed_bash_call(product, support.load_settings(product), sandbox, command, changed=changed)
        assert call.registered, (
            f"`{command}` failed, and {hooks.GENERATED_REL}, generated from {hooks.SOURCE_REL}, registers no "
            f"{hooks.FAILED_CALL_EVENT} command for Bash: no containment check runs after a failed command "
            f"(DEC-596)"
        )
        assert all(result.returncode == 0 for result in call.results), (
            f"`{command}` failed, and a registered {hooks.FAILED_CALL_EVENT} command did not end cleanly: "
            f"{call.describe()}"
        )
        return call

    @needs_rulesync
    def test_a_change_left_out_of_scope_by_a_failed_command_is_reported_and_recorded(
        self, product, session_sandbox,
    ):
        command = "echo changed >> README.md; exit 3"
        call = self._call(product, session_sandbox, command, ["README.md"])
        assert "README.md" in call.report, (
            f"`{command}` failed after changing README.md outside the ticket's paths, and the agent is not told: "
            f"{call.describe()}"
        )
        findings = [json.loads(line) for line in call.new_findings]
        assert any("README.md" in finding.get("paths", []) for finding in findings), (
            f"`{command}`: no finding for README.md was added to {hooks.check_support.FINDINGS_REL}: {findings}"
        )

    @needs_rulesync
    def test_an_acceptance_test_changed_by_a_failed_command_is_restored(self, product, session_sandbox):
        rel = hooks.ACCEPTANCE_FILE
        before = hooks.check_support.read(product, rel)
        command = f"echo changed >> {rel}; exit 1"
        call = self._call(product, session_sandbox, command, [rel])
        assert hooks.check_support.read(product, rel) == before, (
            f"`{command}` by the engineer failed after changing an acceptance test, and {rel} was not restored: "
            f"{call.describe()}"
        )
        assert rel in call.report, f"`{command}`: the agent is not told that {rel} was restored: {call.describe()}"

    @needs_rulesync
    def test_a_failed_command_that_stays_in_scope_is_left_alone(self, product, session_sandbox):
        rel = hooks.IN_SCOPE_FILE
        command = f"echo changed >> {rel}; exit 1"
        call = self._call(product, session_sandbox, command, [rel])
        assert not call.report and not call.new_findings, (
            f"`{command}` changed only {rel}, inside the ticket's paths, and the check did not stay silent: "
            f"{call.describe()}; findings {call.new_findings}"
        )
        assert rel in hooks.check_support.porcelain_all(product), f"`{command}`: the change to {rel} was undone"
