"""Helpers for the cases on the template's rulesync hooks source (DEC-596).

DEC-596: the template's rulesync hooks source gets ``"timeout": 60`` on every
guard hook entry, and the entry that runs the containment check after a failed
tool call. A project's harness settings are generated by rulesync from that
source, so what the kernel template's settings carry (DEC-580) reaches an
adopted project only through it.

What the words are taken to mean:

- **A hook entry of the source** is one object of the list an event name holds
  under ``hooks`` (and under ``hooks`` of a block that overrides one tool, if
  the source has such a block): the object that holds ``command``.
- **A guard hook entry**, **carries the limit**: the words of
  ``tests/acceptance/W1-47/w1_47_hook_time_limit.py`` (DEC-592: every hook entry
  that runs a program of the kernel's hooks folder; only the integer 60).
- **The program of an entry** is the file of the kernel's hooks folder its
  command names. The command line around it (how Python is called, how the
  path is written) is not compared.

The generated settings are judged by W1-47's module itself, so the kernel
template's settings (W1-47), a created project's (W1-39) and the generated ones
(here) are held with the same words.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

_TESTS = Path(__file__).resolve().parent.parent
for _suite in ("W1-03", "W1-05", "W1-47"):
    if str(_TESTS / _suite) not in sys.path:
        sys.path.insert(0, str(_TESTS / _suite))

import w1_03_support as check_support  # noqa: E402  (the fixture ticket, what a hook's result tells the agent)
import w1_05_support as live_support   # noqa: E402  (which registered commands the harness runs, and their input)
import w1_47_hook_time_limit as limit  # noqa: E402  (a guard hook entry, the limit)

REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE_REL = "template/.rulesync/hooks.jsonc"
PROJECT_SOURCE_REL = ".rulesync/hooks.jsonc"
KERNEL_SETTINGS_REL = "template/governance/kernel/settings.json"
KERNEL_HOOKS_REL = "template/governance/kernel/hooks"
GENERATED_REL = ".claude/settings.json"
FAILED_CALL_EVENT = "PostToolUseFailure"       # the harness's event for a failed tool call
# rulesync 24.0.0's name for that event in a hooks source (measured, see the README).
RULESYNC_FAILED_CALL_KEY = "postToolUseFailure"
RULESYNC_AFTER_CALL_KEY = "postToolUse"

ENGINEER = check_support.ENGINEER
TICKET_ID = check_support.TICKET_ID
TICKET_PATHS = ("src/app/**", "tests/unit/**")
IN_SCOPE_FILE = "src/app/main.py"
ACCEPTANCE_FILE = check_support.ACCEPTANCE_FILE
COMMAND_TIMEOUT_S = 30.0


# --------------------------------------------------------------------------
# Reading the source (JSON with comments)
# --------------------------------------------------------------------------

def _without_comments(text):
    """``text`` without ``//`` and ``/* */`` comments and without a comma before ``}`` or ``]``."""
    out, i, in_string = [], 0, False
    while i < len(text):
        char = text[i]
        if in_string:
            out.append(char)
            if char == "\\" and i + 1 < len(text):
                out.append(text[i + 1])
                i += 1
            elif char == '"':
                in_string = False
        elif char == '"':
            in_string = True
            out.append(char)
        elif text.startswith("//", i):
            end = text.find("\n", i)
            i = len(text) if end < 0 else end
            continue
        elif text.startswith("/*", i):
            end = text.find("*/", i + 2)
            i = len(text) if end < 0 else end + 2
            continue
        elif char in "}]":
            while out and out[-1].isspace():
                out.pop()
            if out and out[-1] == ",":
                out.pop()
            out.append(char)
        else:
            out.append(char)
        i += 1
    return "".join(out)


def parse_source(text, name=SOURCE_REL):
    """The object a hooks source holds. A number keeps the kind it was written as (``60`` or ``60.0``)."""
    try:
        data = json.loads(_without_comments(text))
    except ValueError as exc:
        raise AssertionError(f"{name} is not JSON with comments: {exc}") from None
    assert isinstance(data, dict), f"{name} does not hold an object"
    return data


def load_source(path=None, name=SOURCE_REL):
    path = Path(path) if path is not None else REPO_ROOT / SOURCE_REL
    assert path.is_file(), f"{name} does not exist"
    return parse_source(path.read_text(encoding="utf-8"), name)


def write_source(path, source):
    Path(path).write_text(json.dumps(source, indent=2) + "\n", encoding="utf-8")


def kernel_programs():
    """The file names of the kernel template's hook programs."""
    return limit.program_names(REPO_ROOT / KERNEL_HOOKS_REL)


def kernel_settings():
    return limit.load(REPO_ROOT / KERNEL_SETTINGS_REL, KERNEL_SETTINGS_REL)


# --------------------------------------------------------------------------
# The source's hook entries
# --------------------------------------------------------------------------

def source_entries(source):
    """Every hook entry of a source object: ``(where, entry)``, and what is not of the stated shape."""
    entries, misshapen = [], []
    blocks = [("hooks", source.get("hooks"))]
    blocks += [(f"{key}.hooks", value["hooks"]) for key, value in source.items()
               if key != "hooks" and isinstance(value, dict) and "hooks" in value]
    if not isinstance(source.get("hooks"), dict):
        misshapen.append("the object holds no `hooks` map")
    for label, block in blocks:
        if not isinstance(block, dict):
            continue
        for event, listed in block.items():
            if not isinstance(listed, list):
                misshapen.append(f"{label}.{event}: not a list of hook entries")
                continue
            for index, entry in enumerate(listed):
                if not isinstance(entry, dict):
                    misshapen.append(f"{label}.{event}[{index}]: not an object")
                    continue
                entries.append((f"{label}.{event}[{index}]", entry))
    return entries, misshapen


def source_guard_entries(source, programs):
    return [(where, entry) for where, entry in source_entries(source)[0] if limit.is_guard_entry(entry, programs)]


def source_faults(source, programs):
    """One sentence for each guard hook entry of the source that does not carry the limit, and for each misshapen part."""
    entries, found = source_entries(source)
    found = list(found)
    for where, entry in entries:
        if not limit.is_guard_entry(entry, programs) or limit.carries_the_limit(entry):
            continue
        if limit.LIMIT_KEY not in entry:
            state = f"carries no `{limit.LIMIT_KEY}`"
        else:
            state = f"carries `{limit.LIMIT_KEY}`: {entry[limit.LIMIT_KEY]!r}, which is not the whole number {limit.LIMIT_S}"
        found.append(f"{where}, command `{entry.get('command')}`, {state}")
    return found


# --------------------------------------------------------------------------
# What a settings object registers
# --------------------------------------------------------------------------

def program_of(entry, programs):
    """The kernel hook program the entry's command names; None when it names none or more than one."""
    command = entry.get("command")
    named = [name for name in programs if isinstance(command, str) and name in command]
    return named[0] if len(named) == 1 else None


def registered(settings, programs, event):
    """What a settings object registers under ``event`` for the kernel's hook programs:
    the sorted list of ``(matcher or None, program, the value under timeout or None)``, one for each guard hook entry."""
    found = []
    for where, group, entry in limit.guard_entries(settings, programs):
        if where.startswith(f"{event}["):
            found.append((group.get("matcher"), program_of(entry, programs), entry.get(limit.LIMIT_KEY)))
    return sorted(found, key=repr)


def guard_events(settings, programs):
    """The events under which a settings object registers a guard hook entry, in the file's order."""
    events = []
    for where, _group, _entry in limit.guard_entries(settings, programs):
        event = where.split("[", 1)[0]
        if event not in events:
            events.append(event)
    return events


def containment_program(programs):
    """The program the kernel template's settings register for a failed Bash call."""
    found = {program for matcher, program, _limit in registered(kernel_settings(), programs, FAILED_CALL_EVENT)
             if live_support.matcher_matches(matcher, "Bash")}
    assert len(found) == 1 and None not in found, (
        f"{KERNEL_SETTINGS_REL} registers {sorted(map(str, found))} for a failed Bash call; one program is expected"
    )
    return found.pop()


# --------------------------------------------------------------------------
# One Bash call of a session, through the commands the generated settings register
# --------------------------------------------------------------------------

PRODUCT_FILES = {
    "README.md": "# Product\n",
    ".gitignore": ".gov-runtime/\n__pycache__/\n",
    IN_SCOPE_FILE: "VALUE = 1\n",
    "tests/unit/test_main.py": "VALUE = 1\n",
    ACCEPTANCE_FILE: "VALUE = 1\n",
    "docs/notes.md": "notes\n",
}


def add_product_work(project):
    """Give the generated project a product's files and one engineer ticket in progress, and commit.

    The project holds no ``gov`` package of its own: a product repository has the package installed.
    """
    project = Path(project)
    files = dict(PRODUCT_FILES)
    files[f".tickets/{TICKET_ID}.md"] = check_support.ticket_text(allowed_paths=TICKET_PATHS)
    for rel, text in files.items():
        path = project / rel
        assert not path.exists(), f"{rel} is already in the generated project"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    check_support.git(project, "add", "-A")
    check_support.git(project, "commit", "-q", "-m", "a product's files and one ticket")
    return project


def make_session_sandbox(base):
    """A home and a temporary folder outside the project, with the ``gov`` package installed for that home.

    Nothing is installed by a test. The package of this worktree is made importable the way an editable
    install does it: a path file in the user site folder of the stand-in home. A registered command that
    sets ``PYTHONPATH`` itself still finds it, as it would find an installed package.
    """
    box = live_support.make_sandbox(base)
    env = live_support.command_environment(box.home, box)
    site = subprocess.run([sys.executable, "-c", "import site; print(site.getusersitepackages())"],
                          capture_output=True, text=True, env=env, check=True).stdout.strip()
    assert site.startswith(str(box.home) + os.sep), f"the user site folder {site} is not under the stand-in home"
    Path(site).mkdir(parents=True, exist_ok=True)
    (Path(site) / "gov-of-this-worktree.pth").write_text(str(REPO_ROOT / "src") + "\n", encoding="utf-8")
    return box


@dataclass(frozen=True)
class FailedCall:
    registered: tuple       # the commands the settings register for the failed call
    results: tuple          # one live_support.CommandResult for each
    report: str             # the text that reaches the agent
    new_findings: tuple     # the lines added to the findings file since the call began
    bash_exit: int

    def describe(self):
        return "; ".join(result.describe() for result in self.results) or "no command is registered"


_CALLS = iter(range(1, 1_000_000))


def failed_bash_call(project, settings, sandbox, command, changed=(), role=ENGINEER, ticket=TICKET_ID):
    """One whole Bash call that fails, as a session makes it, through the commands ``settings`` register:
    the PreToolUse commands for Bash, the command for real, then the commands for the failed-call event with
    the input the harness gives after a failed tool call. The registered commands are run in the project's
    root folder, as the suites' other live-hook cases run them (W1-05).
    """
    project = Path(project)
    number = next(_CALLS)
    tool_use_id = f"toolu_w1_38_{number:04d}"
    directory = sandbox.home.parent / "calls"
    directory.mkdir(exist_ok=True)
    script = directory / f"call-{number:04d}.sh"
    script.write_text(command + "\n", encoding="utf-8")
    call = f"bash {script}"
    tool_input = {"command": call, "description": "W1-38 acceptance call"}
    seen = len(check_support.finding_lines(project))

    def run(event, extra=None):
        stdin = live_support.hook_input(project, sandbox, event, "Bash", tool_input, tool_use_id=tool_use_id)
        stdin.update(extra or {})
        commands = live_support.hook_commands(settings, event, "Bash")
        results = []
        for registered_command in commands:
            try:
                proc = subprocess.run(["sh", "-c", registered_command], input=json.dumps(stdin),
                                      capture_output=True, text=True, cwd=str(project),
                                      env=live_support.command_environment(project, sandbox, role, ticket),
                                      timeout=COMMAND_TIMEOUT_S, check=False)
                results.append(live_support.CommandResult(registered_command, proc.returncode, proc.stdout,
                                                          proc.stderr))
            except subprocess.TimeoutExpired:
                results.append(live_support.CommandResult(registered_command, None, "", "timed out"))
        return commands, results

    _commands, before = run("PreToolUse")
    assert before, f"{GENERATED_REL} registers no PreToolUse command for Bash"
    refused = [result for result in before
               if check_support._guard_decision(result.returncode, result.stdout) != "allow"]
    assert not refused, (
        f"the registered PreToolUse commands did not let the fixture call `{call}` through, so no Bash call "
        f"would follow: " + "; ".join(result.describe() for result in refused)
    )
    bash = live_support.run_bash(project, call, sandbox)
    assert bash.returncode != 0, f"the fixture command `{command}` did not fail: exit {bash.returncode}"
    status = check_support.porcelain_all(project)
    for rel in changed:
        assert rel in status, f"the fixture command `{command}` did not change {rel}:\n{status}"
    commands, after = run(FAILED_CALL_EVENT, {"error": f"Exit code {bash.returncode}\n{bash.stderr}".strip()})
    report = "\n".join(
        text for text in (check_support.agent_text(result.returncode, result.stdout, result.stderr)
                          for result in after) if text
    )
    return FailedCall(tuple(commands), tuple(after), report,
                      tuple(check_support.finding_lines(project)[seen:]), bash.returncode)
