"""W1-33 -- the project roster: one entry per Wave 1 role.

DEC-066: "Roles are subagent definitions generated by rulesync from kernel role
files plus a project roster". MR-5: "Each Wave 1 role exists ... and a ticket's
role field names one of them".

KPI success 1 [CAP-22.a]: the five roles. The roster holds them beside the
research role W1-46 delivered, six entries in all. An entry has the keys the
research entry already has: ``role_file``, ``agent``, and for a launched worker
``session`` and ``network_profile``.

KPI success 3 [CAP-58.b]: "the launcher's network profile, which the role
definition names (empty for engineer, test designer and auditor ...)".

KPI success 5: "W1-33 does not redefine it (DEC-163)": the research entry.
"""

from __future__ import annotations

import pytest

import w1_33_support as support


def _entry(role):
    roles = support.load_roster()
    assert role in roles, f"{support.ROSTER_REL} has no entry for {role} (it holds {sorted(roles)})"
    assert isinstance(roles[role], dict), f"the roster entry of {role} is not a mapping"
    return roles[role]


def test_the_roster_holds_the_five_roles_and_research_and_no_other():
    assert sorted(support.load_roster()) == sorted(support.ROLES + (support.RESEARCH,))


@pytest.mark.parametrize("role", support.ROLES)
def test_the_entry_names_the_role_s_kernel_role_file_and_its_definition(role):
    entry = _entry(role)
    assert entry.get("role_file") == support.role_file_rel(role), f"role_file of {role}: {entry.get('role_file')!r}"
    assert (support.REPO_ROOT / support.role_file_rel(role)).is_file(), f"{support.role_file_rel(role)} does not exist"
    assert entry.get("agent") == support.agent_rel(role), f"agent of {role}: {entry.get('agent')!r}"


@pytest.mark.parametrize("role", support.EMPTY_PROFILE_ROLES)
def test_a_launched_worker_s_entry_names_its_session_and_the_empty_profile(role):
    entry = _entry(role)
    assert entry.get("session") == f"gov launch {role} <ticket>", f"session of {role}: {entry.get('session')!r}"
    assert "empty" in str(entry.get("network_profile", "")).lower(), (
        f"network_profile of {role} is {entry.get('network_profile')!r}, not the empty profile (DEC-158)"
    )


@pytest.mark.parametrize("role", support.NOT_LAUNCHED)
def test_a_role_the_launcher_does_not_start_has_no_launched_session(role):
    """The launcher starts engineer, test designer, auditor and research only (DEC-161)."""
    assert "gov launch" not in str(_entry(role).get("session", "")), f"the roster says {role} is started by gov launch"


def test_every_ticket_s_role_is_in_the_roster():
    """MR-5: "a ticket's role field names one of them"."""
    roles = support.load_roster()
    unknown = {role: names[:3] for role, names in support.ticket_roles().items() if role not in roles}
    assert not unknown, f"tickets name roles the roster does not hold: {unknown}"


def test_the_research_entry_is_unchanged():
    """Green before implementation; it must stay green. The entry's lines stay as W1-46 wrote them."""
    assert support.load_roster().get(support.RESEARCH) == support.RESEARCH_ROSTER_ENTRY
    lines = support.read_committed(support.ROSTER_REL).splitlines()
    wanted = list(support.RESEARCH_ROSTER_LINES)
    assert any(lines[index:index + len(wanted)] == wanted for index in range(len(lines))), (
        f"the research entry of {support.ROSTER_REL} is no longer the five lines W1-46 wrote"
    )
