#!/usr/bin/env python3
"""P2-AR-0007 AC-8: verify zeta-r's artifact-flow-coverage-matrix.yaml before carrying it forward.

For every cell, every cited observation '<OBS-id> PASS|FAIL' is looked up in (a) zeta-r's committed outputs and (b) the
outputs regenerated by RERUN-family-probes.sh in the disposable clone; the cited status must equal both. Cells whose
status is EVIDENCED must cite at least one PASS; GAP cells must not rest on a PASS alone.

usage: python3 AC08-verify-artifact-flow-matrix.py <worktree-root> <clone-root>
"""
import glob
import os
import re
import sys

import yaml

wt, clone = sys.argv[1], sys.argv[2]
Z = "release/capability-baseline/audit-0/zeta-r"


def obs_map(root):
    m = {}
    for f in glob.glob(os.path.join(root, Z, "evidence", "*.out")):
        for line in open(f, errors="replace"):
            mm = re.match(r"^OBS (\S.*?): (PASS|FAIL)", line)
            if mm:
                m[(os.path.basename(f), mm.group(1))] = mm.group(2)
    return m


committed, rerun = obs_map(wt), obs_map(clone)
ids_by_file = {}
for (f, i) in committed:
    ids_by_file.setdefault(f, []).append(i)
for f in ids_by_file:
    ids_by_file[f].sort(key=len, reverse=True)

mx = yaml.safe_load(open(os.path.join(wt, Z, "artifact-flow-coverage-matrix.yaml")))
cols = mx["columns"]
n_cells = n_cited = n_ok = 0
problems = []
status_count = {}
for row in mx["rows"]:
    for col in cols:
        cell = row.get(col)
        if col == "qualification_challenge":
            n_cells += 1
            if not cell or not isinstance(cell, str):
                problems.append((row["artefact_type"], col, "no dedicated qualification challenge"))
            continue
        if not isinstance(cell, dict):
            problems.append((row["artefact_type"], col, "cell missing"))
            continue
        n_cells += 1
        st = cell.get("status")
        status_count[st] = status_count.get(st, 0) + 1
        cited = []
        for ev in cell.get("evidence") or []:
            m = re.match(r"(evidence/)?(\S+\.out)\s*(.*)", ev)
            if not m:
                continue
            fname, rest = m.group(2).split("/")[-1], m.group(3)
            for oid in ids_by_file.get(fname, []):
                for mm in re.finditer(re.escape(oid) + r"\s+(PASS|FAIL)", rest):
                    cited.append((fname, oid, mm.group(1)))
                rest = re.sub(re.escape(oid) + r"\s+(PASS|FAIL)", "", rest)
        for fname, oid, s in cited:
            n_cited += 1
            c, r = committed.get((fname, oid)), rerun.get((fname, oid))
            if s == c == r:
                n_ok += 1
            else:
                problems.append((row["artefact_type"], col, f"{fname} {oid}: cited {s}, committed {c}, rerun {r}"))
        passes = [s for _, _, s in cited if s == "PASS"]
        if st == "EVIDENCED" and not passes and cited:
            problems.append((row["artefact_type"], col, "EVIDENCED cell cites no PASS observation"))
        if st == "GAP" and cited and all(s == "PASS" for _, _, s in cited):
            problems.append((row["artefact_type"], col, "GAP cell cites only PASS observations"))
print(f"[AC-8] matrix rows={len(mx['rows'])} columns={len(cols)} cells={n_cells} status_counts={status_count}")
print(f"[AC-8] cited observations={n_cited}; matching committed AND rerun status={n_ok}")
print(f"[AC-8] problems ({len(problems)}):")
for p in problems:
    print("   ", p)
print(f"[AC-8] determination recorded by zeta-r: {mx['ac8_determination']['determination']}; rejection conditions triggered: "
      f"{[c['triggered'] for c in mx['ac8_determination']['rejection_conditions']]}")
