#!/usr/bin/env python3
"""P2-AR-0007 synthesis: compare every family's committed probe outputs (audits of record) with the outputs regenerated
by RERUN-family-probes.sh inside a disposable clone of the same commit.

Two comparisons per .out file:
  1. marker level  - for families that emit per-check verdict markers, the (check-id -> PASS/FAIL) map must be identical:
       beta-r   lines "[PASS] ..." / "[FAIL] ..."     (key = normalised text of the line)
       delta-r  lines "CHECK <id> PASS|FAIL ..."
       zeta-r   lines "OBS <id>: PASS|FAIL ..."
       alpha-r  lines "[TAG] ..." (key = tag + ordinal within the file; value = normalised line)
  2. normalised full text - scratch paths, hex digests, timestamps, durations, random ids and ports are masked; every
     remaining differing line is printed so a human can adjudicate it.

usage: python3 COMPARE-family-outputs.py <worktree-root> <clone-root> [family ...]
The committed outputs are read from <worktree-root>; regenerated ones from <clone-root>. Nothing is written except stdout.
"""
import difflib
import os
import re
import sys

FAMILIES = ["alpha-r", "beta-r", "gamma-r", "delta-r", "epsilon-r", "zeta-r"]
SUB = [
    (re.compile(r"/tmp/[^\s'\"\],)}]*"), "<PATH>"),
    (re.compile(r"/home/[^\s'\"\],)}]*"), "<PATH>"),
    (re.compile(r"\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?"), "<TS>"),
    (re.compile(r"\b[0-9a-f]{7,64}\b"), "<HEX>"),
    (re.compile(r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b"), "<UUID>"),
    (re.compile(r"\b\d+(\.\d+)?\s*(ms|µs|us|s|sec|seconds)\b"), "<DUR>"),
    (re.compile(r"(duration|elapsed|latency)[_a-z]*[\"']?\s*[:=]\s*[\d.]+"), r"\1=<N>"),
    (re.compile(r"\b(S|SESS|sess|session)-[A-Za-z0-9_-]{6,}\b"), "<SESSION>"),
    (re.compile(r"\binode[ =:]+\d+"), "inode=<N>"),
    (re.compile(r"\bpid[ =:]+\d+"), "pid=<N>"),
    (re.compile(r"[A-Za-z0-9+/]{40,}={0,2}"), "<B64>"),
    (re.compile(r"XXXXXX|[A-Za-z0-9_]{8}(?=/)"), "<RND>"),
]


def norm(line):
    s = line.rstrip("\n")
    for rx, rep in SUB:
        s = rx.sub(rep, s)
    return re.sub(r"\s+", " ", s).strip()


def markers(family, lines):
    out = {}
    if family == "beta-r":
        for l in lines:
            m = re.match(r"^\[(PASS|FAIL)\]\s*(.*)", l)
            if m:
                out[norm(m.group(2))[:160]] = m.group(1)
    elif family == "delta-r":
        for l in lines:
            m = re.match(r"^CHECK (\S+) (PASS|FAIL)", l)
            if m:
                out[m.group(1)] = m.group(2)
    elif family == "zeta-r":
        for l in lines:
            m = re.match(r"^OBS (\S.*?): (PASS|FAIL)", l)
            if m:
                out[m.group(1)] = m.group(2)
    elif family == "alpha-r":
        cnt = {}
        for l in lines:
            m = re.match(r"^\[([A-Z0-9][A-Za-z0-9_-]*)\]", l)
            if m:
                t = m.group(1)
                cnt[t] = cnt.get(t, 0) + 1
                out[f"{t}#{cnt[t]}"] = norm(l)
    return out


def main():
    wt, clone = sys.argv[1], sys.argv[2]
    fams = sys.argv[3:] or FAMILIES
    total_files = total_diff_files = 0
    for fam in fams:
        a_dir = os.path.join(wt, "release/capability-baseline/audit-0", fam, "evidence")
        b_dir = os.path.join(clone, "release/capability-baseline/audit-0", fam, "evidence")
        print(f"\n######## {fam}")
        for fn in sorted(os.listdir(a_dir)):
            if not fn.endswith(".out") and fn != "run-all.log":
                continue
            a = os.path.join(a_dir, fn)
            b = os.path.join(b_dir, fn)
            if not os.path.exists(b):
                continue
            with open(a, errors="replace") as f:
                al = f.readlines()
            with open(b, errors="replace") as f:
                bl = f.readlines()
            regenerated = os.path.getmtime(b) > os.path.getmtime(os.path.join(clone, "Cargo.toml")) + 30
            if not regenerated:
                print(f"== {fn}: NOT REGENERATED by the re-run (not produced by the family's probe runner)")
                continue
            if open(a, "rb").read() == open(b, "rb").read():
                total_files += 1
                print(f"== {fn}: REGENERATED, BYTE-IDENTICAL")
                continue
            total_files += 1
            ma, mb = markers(fam, al), markers(fam, bl)
            mk = ""
            if ma or mb:
                changed = sorted(k for k in set(ma) | set(mb) if ma.get(k) != mb.get(k))
                mk = f" markers={len(ma)}/{len(mb)} changed={len(changed)}"
            na = [norm(x) for x in al]
            nb = [norm(x) for x in bl]
            diff = [d for d in difflib.unified_diff(na, nb, lineterm="", n=0) if d[:1] in "+-" and not d.startswith(("+++", "---"))]
            status = "SAME(normalised)" if not diff else f"DIFF {len(diff)} lines"
            if diff:
                total_diff_files += 1
            print(f"== {fn}: {status}{mk}")
            if ma or mb:
                for k in sorted(k for k in set(ma) | set(mb) if ma.get(k) != mb.get(k))[:60]:
                    print(f"   MARKER {k!r}: committed={ma.get(k)!r} rerun={mb.get(k)!r}")
            for d in diff[:80]:
                print("   " + d[:300])
            if len(diff) > 80:
                print(f"   ... {len(diff) - 80} more")
    print(f"\n# files compared: {total_files}; files with normalised differences: {total_diff_files}")


if __name__ == "__main__":
    main()
