#!/usr/bin/env bash
# O3 — Independent test authorship (Contract v3 lines 782-785; framework §62 last paragraph).
source "$(dirname "$0")/lib.sh"
B=$(base_project)
RF=$(readiness_full)

say "A. implementation task is blocked while its feature's acceptance obligation is not independent (DAG gate)"
R=$(clone "$B" o3-a)
yw "$R" spec/features/F-0001.yaml "{'id':'F-0001','type':'feature','title':'Ledger totals','status':'ACTIVE','readiness':$RF,'scenarios':['SCN-0001']}"
yw "$R" spec/scenarios/SCN-0001.yaml "{'id':'SCN-0001','type':'scenario','title':'totals','status':'ACTIVE','feature':'F-0001','given':['g'],'when':['w'],'then':['t']}"
yw "$R" spec/tests/TO-0001.yaml "{'id':'TO-0001','type':'test-obligation','title':'acceptance totals','status':'ACTIVE','family':'acceptance','feature':'F-0001','author_role':'backend-engineer'}"
T=$(new_task "$R" implementation 'src/**,tests/**' --feature F-0001); echo "task: $T"
gp "$R" "{'runnable':r['runnable'],'blocked':r['blocked']}" task dag

say "B. the implementer's own role declares independence; the gate opens (independence is a self-declared boolean)"
ye "$R" spec/tests/TO-0001.yaml "d['independent_of_implementer']=True"
note "TO-0001 author_role=backend-engineer (the implementing role), independent_of_implementer=true"
gp "$R" "{'runnable':r['runnable'],'blocked':r['blocked']}" task dag
gp "$R" "[(f['severity'],f['message'][:140]) for f in r['findings'] if f['family']=='product_traceability']" audit --no-persist --family product_traceability
note "same session S-builder claims the task and closes it citing the same test file as evidence:"
( cd "$R" && git add -A && git commit -qm specs ) >/dev/null 2>&1
SESS=S-builder ROLE=backend-engineer gp "$R" "ok" task claim "$T"
printf '\n#[test]\nfn builder_written_acceptance() { assert_eq!(1+1, 2); }\n' >> "$R/tests/ledger_test.rs"
g "$R" rebuild-memory --incremental >/dev/null 2>&1
report_json "$SCRATCH/o3-report.json" passed tests/ledger_test.rs "'evidence':['tests/ledger_test.rs::builder_written_acceptance'],'tests':{'status':'passed','independent':True,'author':'S-builder'}"
SESS=S-builder ROLE=backend-engineer gp "$R" "{'ok':ok,'task_status':(r or {}).get('task_status'),'error':e.get('code') if e else None}" task close "$T" --report "$SCRATCH/o3-report.json"
note "report record as stored (no distinction between builder regression evidence and independent evidence):"
python3 -c "import yaml; d=yaml.safe_load(open('$R/spec/reports/RPT-0001.yaml')); print({k:d.get(k) for k in ['task','session','role','tests','evidence','state_class']})"

say "C. adoption: planner may not review its own plan (session equality check)"
M="$SCRATCH/o3-mig"; rm -rf "$M" "$M.machine"; cp -r "$WT/fixtures/migration/project" "$M"; git_base "$M" >/dev/null 2>&1
for st in baseline inventory classify map plan test-design; do printf '%s: ' "$st"; SESS=S-planner gp "$M" "ok if ok else e.get('code')" adopt $st; done
T0=$(python3 -c "import yaml; d=yaml.safe_load(open('$M/spec/audits/GOVERNANCE-ADOPTION/06-migration-tests.yaml')); print(len(d['tests']))")
H0=$(sha256sum "$M/spec/audits/GOVERNANCE-ADOPTION/06-migration-tests.yaml" | cut -c1-16)
echo "planner-scaffolded tests: $T0 (sha256 $H0...)"
printf 'review by planner session: '; SESS=S-planner gp "$M" "ok if ok else (e.get('code'), e.get('message')[:120])" adopt review --verdict MIGRATION_PLAN_APPROVED

say "D. the same caller passes any other session string; approval is recorded with ZERO reviewer-added tests"
printf 'review with --reviewer-session S-anything: '; SESS=S-planner gp "$M" "{'ok':ok,'r':r,'err':e.get('code') if e else None}" adopt review --verdict MIGRATION_PLAN_APPROVED --reviewer-session S-anything
H1=$(sha256sum "$M/spec/audits/GOVERNANCE-ADOPTION/06-migration-tests.yaml" | cut -c1-16)
echo "tests file unchanged by review: $H0 == $H1"
grep -F 'MIGRATION_PLAN_APPROVED' "$M/spec/audits/GOVERNANCE-ADOPTION/06-INDEPENDENT-MIGRATION-TEST-DESIGN.md" | tail -1

say "E. memory held-out regression set is generated by the builder from the live index at gov init (not verifier-authored)"
python3 -c "import yaml; d=yaml.safe_load(open('$B/governance/tests/memory/heldout.yaml')); print({'generated_by':d.get('generated_by'),'queries':len(d['queries']),'note':d.get('note')})"
